// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PassSystemTD.Data;

#nullable disable

namespace PassSystemTD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250306173034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PassStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Proof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PassId");

                    b.ToTable("Proofs");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDean")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4042310-415c-4653-9619-fa69374e10e4"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("44b52025-d0fb-4661-af7e-054259cf59de"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("52d127d4-f139-4afa-925d-60786c8315de"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("dc345da4-1c83-4f64-a24f-18ce954f0f51"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("99039304-1558-4b4f-b671-0d990e92183f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("1297ff48-9a09-490d-9fed-aa814ad346f5"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c1ad356b-1e9b-49a4-a697-19af1d30d358"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("95f20317-824e-4301-b72a-583ae71d2773"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("2719ca01-46ce-4a9a-b8f4-c21ebde0812e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b84b781f-b1e1-4845-ac80-92e879578278"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("1b91b677-4762-4b80-b3c4-20bc56b6f509"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d43f3615-aa5c-47b0-88ca-ae8948a2b2a8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("61ef5c48-4ffb-4812-80c3-2cd4bd9db6ab"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c95b5af8-a51c-4b0c-9627-c67e3bff0dfe"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6c1c673b-65d4-45f8-b942-b8efc3c657d3"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("d42c2753-eedb-4fb4-8cfb-684419d76845"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d94b84ec-c704-4c90-a3a7-77df4d2f227b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("66bf09e7-4ee0-4bc1-93a2-56d563d1ef76"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("9bd731e2-9a4a-447c-9a1d-a72efb657b73"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("7a7845b6-ad09-42a7-838f-4771a59893eb"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("c54893e1-fd86-42fa-bedc-f4630e00e490"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("38df980f-ae25-4f71-8b26-bb01da6979cd"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("8b5fb264-2956-4164-9bb4-96df63856d76"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("a5fb46fb-d255-4b2f-b58e-381406fdcee8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("cd8339c9-10de-4874-9a43-76e1305db263"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("d8494d79-62da-421f-a137-4ab5205715e3"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("7ecb0217-0234-4fa9-94d1-0535596f0ae0"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("31823557-58bf-488f-a26b-39980ba2c812"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("bff4b66a-073c-4291-979a-4df235d5d385"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("495875cb-2e46-4b7d-8c33-6bab62c1ba2d"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("b9e441b5-9463-4f1b-a1d5-bcef8cdc3e7a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("9cb59595-73bb-4a8f-9b24-95c8e4c9c6b4"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("f37bb89a-0099-424f-b896-5aeccbbe3714"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("12c34c8d-a16c-4e0e-a00a-14c98b63f769"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("804f625a-adc4-4ba3-91af-712dd9787199"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("39caa98a-3ad0-4daf-afb1-2db9b16be080"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b2879535-78db-47f4-a22f-610fb4c78dfb"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("484b33b6-5073-40a5-95d8-ffd251222643"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b9018763-6dc7-4173-9e50-05f8c6720d90"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("746889a9-db39-4b01-907c-e986758a8533"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("28a0d125-d6ae-41c8-800a-2cab8cdc2846"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d1a771b4-2db2-44d0-bb46-d15e53b8ffdc"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("7d720cd9-584d-456f-9900-17be2be0f4ab"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("eb7b4660-6b58-4873-aff9-56946923f0af"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c1b0b276-461f-40cd-8d1c-4746f2afc943"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("3a29e92e-268a-4fd7-98d1-b805112825b8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("05a7d2d1-298b-4037-9a7d-97ff1964103c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("aa3de1e0-9e51-405e-8d22-0fde889cf9a5"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c85964dd-4dda-4109-9302-a4847b25b9c2"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("35ad2725-3e8a-43b0-826d-aee94c652e9b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("048ce841-8e1f-4920-ad33-b2c73f37481e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("2e037cfb-cf6e-4def-8ece-69839d9fa57b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("0062ebc0-6a55-40c6-bc17-8b637606802b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b1b12b7c-04fc-44b9-8e85-6200490848c2"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("03d0c348-05c1-46c0-8436-ee909b867986"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("e09d7938-7b33-49b7-bcd5-e58659c05477"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1453afb3-acc5-4450-97c6-1d429c139c44"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1d5a4192-4e0c-42f4-9e71-2ae9ac920157"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("f89c5788-754e-4b3a-bec4-62426a231d92"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("50d9194b-d37a-49d6-b740-07686bee4f58"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("4a72700e-1b8e-43f4-8771-329d8dbad9d4"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("e30c40e3-4ddf-43e7-9a99-db71f9719f48"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("35a74d04-b7d1-4666-8cb4-8c2a2626a1c3"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("41f2b629-08a5-4f2b-807b-7ff693a55826"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("78dfb8ca-17c4-41f0-8bcf-32d1ddc1852e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("2dfa4903-5e71-4313-8973-308f4c548f29"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("67e8aae7-4472-45ef-a7b7-44d917479b41"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("487b7ea9-c187-4b95-8abf-81825d0b0d40"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("4e0556e5-5718-4c34-9267-787580fc5e72"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("24ef338e-856c-43f6-ba20-4f915302e570"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("e2a71446-03fd-4d0f-94e7-d254e5343293"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("36d19dcf-027e-4062-9ab3-84ecc9473163"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("a19c05cb-1309-4067-a5b9-18df99f7e2b2"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("31b670f1-51ed-4c31-ac0f-03ffc4b25395"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("0f342f9e-e39f-42b8-b60b-d07ec811b2aa"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("899a776b-e1d9-4cb3-a951-fdd2c477a871"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("376447ee-9c9a-433b-8c1d-2f852c6d8db1"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("082cf2ff-9a2f-4893-b73b-f42999a2ac99"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("33652314-82a5-43d0-b62c-f0dc0e26a8d0"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("4d1f0e58-1643-4ab5-af89-95dc0b2f0539"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("f51844af-a9fa-42e9-aa39-4708de91ac3d"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("59255312-aa0c-4ae9-8d0c-9cbc43e30a4f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("7b37bd1f-fcc0-4987-a482-2d576cc6a912"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("9e9b8b13-969c-4378-8921-88a499085af6"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("9f0d96d2-2fbc-49a4-9ad1-c4f911ed2094"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("e4421306-7fb1-45fe-b0ae-67c93282cf1d"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("eff3c3bd-519d-4d1c-adac-62d3d4020f7e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6b9f4bd2-531e-43bf-a8b6-fd085b4cef0c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("ebb7f294-5a1e-407c-9326-250d54e28420"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("17c3bd48-27b6-431c-82e5-2241353b2cb3"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("ba42f8c7-6ddf-49de-add7-1ca800fa0819"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("f5f7d93e-fe3b-45a7-ac3c-33f4eea6c413"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("192791a8-eddd-42a6-92c4-db1b1a1c4185"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("9f83adbb-10d2-422f-9a01-4a1984599190"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c81d6c63-b1da-47e0-8cc6-ea7f4eefb634"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("668a4de0-c88e-4aa4-bdb4-61a620ae39be"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("04c1bf20-54a3-4667-b1de-cf198424a5db"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("38450798-b67a-4651-9f21-dd2f71a04fbc"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("2296497b-9071-4268-a2c0-9718e95425fe"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("47a4bb3b-d961-43bf-93f6-f77a6ffcd297"),
                            IsAdmin = true,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        });
                });

            modelBuilder.Entity("PassSystemTD.Entities.TokenEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Token");

                    b.ToTable("BannedTokens");
                });

            modelBuilder.Entity("PassSystemTD.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4042310-415c-4653-9619-fa69374e10e4"),
                            Email = "user1@example.com",
                            Gender = 1,
                            Name = "User1",
                            Password = "$2a$11$CtMXIImm8/Aa7obPkyB/pO3IpSum8rCF4j4L.bbwSYqhDuAtc5yoW"
                        },
                        new
                        {
                            Id = new Guid("44b52025-d0fb-4661-af7e-054259cf59de"),
                            Email = "user2@example.com",
                            Gender = 0,
                            Name = "User2",
                            Password = "$2a$11$e7MngcUOzQ86Fdw5hePd1eZY7IplX02V4FCVsHc1IC6bs919C90vu"
                        },
                        new
                        {
                            Id = new Guid("52d127d4-f139-4afa-925d-60786c8315de"),
                            Email = "user3@example.com",
                            Gender = 1,
                            Name = "User3",
                            Password = "$2a$11$W6BHxUEknCdcg0Anc4ESXODf4OsbrKIHSUZXS.Tp2JhjtbOg4A1MK"
                        },
                        new
                        {
                            Id = new Guid("dc345da4-1c83-4f64-a24f-18ce954f0f51"),
                            Email = "user4@example.com",
                            Gender = 0,
                            Name = "User4",
                            Password = "$2a$11$tIfu1XUMjkoi0Cm8Cjsry.AeiaHHV5vkztLiJOjp2tJ/nhMKbJtKi"
                        },
                        new
                        {
                            Id = new Guid("99039304-1558-4b4f-b671-0d990e92183f"),
                            Email = "user5@example.com",
                            Gender = 1,
                            Name = "User5",
                            Password = "$2a$11$SyNx2zgwPug9EnKzCKfKoe3Ks7izi.uagr9L5/QqhVbdl/DYHOnpG"
                        },
                        new
                        {
                            Id = new Guid("1297ff48-9a09-490d-9fed-aa814ad346f5"),
                            Email = "user6@example.com",
                            Gender = 0,
                            Name = "User6",
                            Password = "$2a$11$HLxB6OR6xZ2O9DpQidZzcuuzpDhgyH0cONEWnOFwupRiXfRil2V/S"
                        },
                        new
                        {
                            Id = new Guid("c1ad356b-1e9b-49a4-a697-19af1d30d358"),
                            Email = "user7@example.com",
                            Gender = 1,
                            Name = "User7",
                            Password = "$2a$11$.XT/tNpe8.R1RPOc2ZQ6aONboplxW3WdthokRbND74iKy5FHiu8iK"
                        },
                        new
                        {
                            Id = new Guid("95f20317-824e-4301-b72a-583ae71d2773"),
                            Email = "user8@example.com",
                            Gender = 0,
                            Name = "User8",
                            Password = "$2a$11$zgw89BuDPmVcYxbfWvxKses97FOcdPd32/hpOAE5WP.4LBdhBVzHy"
                        },
                        new
                        {
                            Id = new Guid("2719ca01-46ce-4a9a-b8f4-c21ebde0812e"),
                            Email = "user9@example.com",
                            Gender = 1,
                            Name = "User9",
                            Password = "$2a$11$NEQZoP0C.QKJtrCFNasE6eUyqr8f2BFKGDtZb.X7iRiHnudj/Ruu2"
                        },
                        new
                        {
                            Id = new Guid("b84b781f-b1e1-4845-ac80-92e879578278"),
                            Email = "user10@example.com",
                            Gender = 0,
                            Name = "User10",
                            Password = "$2a$11$aFBXZzCPW8V/BOh29uLuruduKa1db1dYLzpm8bd14rCOW8Wm1j9Sy"
                        },
                        new
                        {
                            Id = new Guid("1b91b677-4762-4b80-b3c4-20bc56b6f509"),
                            Email = "user11@example.com",
                            Gender = 1,
                            Name = "User11",
                            Password = "$2a$11$ZrlHfLqkdSgKaICFM1RBQu25jy3mZZOxGOqrBPLS1vHKt3Z0YKlLi"
                        },
                        new
                        {
                            Id = new Guid("d43f3615-aa5c-47b0-88ca-ae8948a2b2a8"),
                            Email = "user12@example.com",
                            Gender = 0,
                            Name = "User12",
                            Password = "$2a$11$QgnuxyMXBY4HF6b.TzwZ/ezWUIK4.wJmxaLAc6uapjf2xLQokn/5O"
                        },
                        new
                        {
                            Id = new Guid("61ef5c48-4ffb-4812-80c3-2cd4bd9db6ab"),
                            Email = "user13@example.com",
                            Gender = 1,
                            Name = "User13",
                            Password = "$2a$11$Q9HSNv5yyeqVGL6qw5seqOcDtmAcdKPNQLd5DspeFg/QPhXoQ8uYy"
                        },
                        new
                        {
                            Id = new Guid("c95b5af8-a51c-4b0c-9627-c67e3bff0dfe"),
                            Email = "user14@example.com",
                            Gender = 0,
                            Name = "User14",
                            Password = "$2a$11$wW.MjGMkapPHfdTAwqJg2.8ni3mlm0jcuPGWk8ucHfrWwk5KpA2yy"
                        },
                        new
                        {
                            Id = new Guid("6c1c673b-65d4-45f8-b942-b8efc3c657d3"),
                            Email = "user15@example.com",
                            Gender = 1,
                            Name = "User15",
                            Password = "$2a$11$DDN/YYUqzdjHHtWW22KSae4d/yVJMla60SG68qTeW.tvV1d2kyd5a"
                        },
                        new
                        {
                            Id = new Guid("d42c2753-eedb-4fb4-8cfb-684419d76845"),
                            Email = "user16@example.com",
                            Gender = 0,
                            Name = "User16",
                            Password = "$2a$11$I/yikskcruMLIH7L4p.OEeFol9kwaRNF.QKzKnShPTLbbQVEtAcH."
                        },
                        new
                        {
                            Id = new Guid("d94b84ec-c704-4c90-a3a7-77df4d2f227b"),
                            Email = "user17@example.com",
                            Gender = 1,
                            Name = "User17",
                            Password = "$2a$11$UptlDacpHOH0zVMLX5Fl4O58I9ehA0DIyXcv.bhnUATZOnlHDe7/6"
                        },
                        new
                        {
                            Id = new Guid("66bf09e7-4ee0-4bc1-93a2-56d563d1ef76"),
                            Email = "user18@example.com",
                            Gender = 0,
                            Name = "User18",
                            Password = "$2a$11$ki0KaYEMO33uRwY6bXB5cucuMNIMiWE8npIz5Pwr5V2tWVrPkGGuO"
                        },
                        new
                        {
                            Id = new Guid("9bd731e2-9a4a-447c-9a1d-a72efb657b73"),
                            Email = "user19@example.com",
                            Gender = 1,
                            Name = "User19",
                            Password = "$2a$11$0623zwz7Dc82nZe7uuom7.GC1SCKg2sY42grIW89bRyUTTxTkAyYO"
                        },
                        new
                        {
                            Id = new Guid("7a7845b6-ad09-42a7-838f-4771a59893eb"),
                            Email = "user20@example.com",
                            Gender = 0,
                            Name = "User20",
                            Password = "$2a$11$Bw0jMP8/gFqHFqf4EBvvtez40E04txoWNrLkLhd5p7SRaPtHYqFeO"
                        },
                        new
                        {
                            Id = new Guid("c54893e1-fd86-42fa-bedc-f4630e00e490"),
                            Email = "user21@example.com",
                            Gender = 1,
                            Name = "User21",
                            Password = "$2a$11$W8sTYESm1dIorXmIUqFfx.qzYt9ro4QqK8b78D2vJuTdsW5ZTEZTi"
                        },
                        new
                        {
                            Id = new Guid("38df980f-ae25-4f71-8b26-bb01da6979cd"),
                            Email = "user22@example.com",
                            Gender = 0,
                            Name = "User22",
                            Password = "$2a$11$xN.YC.cf7v8PNmaSpQteRuyf4801Wm5KEpZEnx2LQULub5WEnMzxC"
                        },
                        new
                        {
                            Id = new Guid("8b5fb264-2956-4164-9bb4-96df63856d76"),
                            Email = "user23@example.com",
                            Gender = 1,
                            Name = "User23",
                            Password = "$2a$11$kT1hiHL9qKYTWiecmT08MOnRW9OO2VPzwYf1uXnB1Mhct/lPimnOG"
                        },
                        new
                        {
                            Id = new Guid("a5fb46fb-d255-4b2f-b58e-381406fdcee8"),
                            Email = "user24@example.com",
                            Gender = 0,
                            Name = "User24",
                            Password = "$2a$11$2CClv/NTXbYbKb9nnckSTOwFG6BlCdYlc77/.PJLqx3Gi4r1qch/C"
                        },
                        new
                        {
                            Id = new Guid("cd8339c9-10de-4874-9a43-76e1305db263"),
                            Email = "user25@example.com",
                            Gender = 1,
                            Name = "User25",
                            Password = "$2a$11$a2IRfAGhFDko3Z7e/PihQuYb29.DS.68PElFffOyLLMv5Hn.eLKKW"
                        },
                        new
                        {
                            Id = new Guid("d8494d79-62da-421f-a137-4ab5205715e3"),
                            Email = "user26@example.com",
                            Gender = 0,
                            Name = "User26",
                            Password = "$2a$11$R2oeiQHrPBRD6x6yNmgWRuTNSYQUnzbLqGxM3QxItiZu2GhoaO7xy"
                        },
                        new
                        {
                            Id = new Guid("7ecb0217-0234-4fa9-94d1-0535596f0ae0"),
                            Email = "user27@example.com",
                            Gender = 1,
                            Name = "User27",
                            Password = "$2a$11$Y.cSiN/mBXI37QVUJ4nhMu7ybwDE96eKrnm09/9KECVICNyjiBcUm"
                        },
                        new
                        {
                            Id = new Guid("31823557-58bf-488f-a26b-39980ba2c812"),
                            Email = "user28@example.com",
                            Gender = 0,
                            Name = "User28",
                            Password = "$2a$11$sQE396wQnpqs.prgbsstVebyujk8xJgb/RJ6OTPgn6NDw0QNERiZe"
                        },
                        new
                        {
                            Id = new Guid("bff4b66a-073c-4291-979a-4df235d5d385"),
                            Email = "user29@example.com",
                            Gender = 1,
                            Name = "User29",
                            Password = "$2a$11$wPkyTn7BgovtX3R5qW9Hgu11Ymbrs0wA30Ixb81Zxhw6zppneb..2"
                        },
                        new
                        {
                            Id = new Guid("495875cb-2e46-4b7d-8c33-6bab62c1ba2d"),
                            Email = "user30@example.com",
                            Gender = 0,
                            Name = "User30",
                            Password = "$2a$11$4ehxFVWjFmpmLxyUANc/juTiBVGPQrH8juqKoT6A5.PTKu8TCyR2u"
                        },
                        new
                        {
                            Id = new Guid("b9e441b5-9463-4f1b-a1d5-bcef8cdc3e7a"),
                            Email = "user31@example.com",
                            Gender = 1,
                            Name = "User31",
                            Password = "$2a$11$CdxeCnx7k63xyUWtE2XXoeR9J1kURGQmtAODZktkpL.zNkI.5yaPG"
                        },
                        new
                        {
                            Id = new Guid("9cb59595-73bb-4a8f-9b24-95c8e4c9c6b4"),
                            Email = "user32@example.com",
                            Gender = 0,
                            Name = "User32",
                            Password = "$2a$11$xe5jZxSWIYshdEKED/Q8XeZjzXHsJPxMW/.0cL3/lUEOOncTjFe6S"
                        },
                        new
                        {
                            Id = new Guid("f37bb89a-0099-424f-b896-5aeccbbe3714"),
                            Email = "user33@example.com",
                            Gender = 1,
                            Name = "User33",
                            Password = "$2a$11$Kb59EvEsnYP1eoBa9hR85e0RoYq.XcEv5KA6zm6NTWzQHMHqMpQF."
                        },
                        new
                        {
                            Id = new Guid("12c34c8d-a16c-4e0e-a00a-14c98b63f769"),
                            Email = "user34@example.com",
                            Gender = 0,
                            Name = "User34",
                            Password = "$2a$11$whO.4UJTUKsVUD0N2git1uggVmY3MZmQoLtUmru6wVTm4RBKl4FuG"
                        },
                        new
                        {
                            Id = new Guid("804f625a-adc4-4ba3-91af-712dd9787199"),
                            Email = "user35@example.com",
                            Gender = 1,
                            Name = "User35",
                            Password = "$2a$11$aZhcdlcVYz6ACK54zRgCcOgDmH2svjDMVoHY.7NN2HRd5PTs3LsNq"
                        },
                        new
                        {
                            Id = new Guid("39caa98a-3ad0-4daf-afb1-2db9b16be080"),
                            Email = "user36@example.com",
                            Gender = 0,
                            Name = "User36",
                            Password = "$2a$11$K8lt5vKpuBhTsNOAHp1/OOmXFUPvxcuUD.q4hmMwTBrcoEwnx3Xmi"
                        },
                        new
                        {
                            Id = new Guid("b2879535-78db-47f4-a22f-610fb4c78dfb"),
                            Email = "user37@example.com",
                            Gender = 1,
                            Name = "User37",
                            Password = "$2a$11$l/G/rZI5bt1Gzv3XEGZgq.opvXJws6jps0oZo5drtoPnNF2bEU6Yi"
                        },
                        new
                        {
                            Id = new Guid("484b33b6-5073-40a5-95d8-ffd251222643"),
                            Email = "user38@example.com",
                            Gender = 0,
                            Name = "User38",
                            Password = "$2a$11$T37c1GFuP3YU82NzHd9SEefJAa7.qYcHzVmM9xMvBCbZHlbglLfpK"
                        },
                        new
                        {
                            Id = new Guid("b9018763-6dc7-4173-9e50-05f8c6720d90"),
                            Email = "user39@example.com",
                            Gender = 1,
                            Name = "User39",
                            Password = "$2a$11$6smQJvMqqvK0PCOf6cj78Ok15dKVpHPT1MuqwqCrXBfaVSTktnJti"
                        },
                        new
                        {
                            Id = new Guid("746889a9-db39-4b01-907c-e986758a8533"),
                            Email = "user40@example.com",
                            Gender = 0,
                            Name = "User40",
                            Password = "$2a$11$zKcwI2dxfolX/vLPFF2xAe1nxJArJgAEjX/aXxsm6sSfdMA8p9jQ2"
                        },
                        new
                        {
                            Id = new Guid("28a0d125-d6ae-41c8-800a-2cab8cdc2846"),
                            Email = "user41@example.com",
                            Gender = 1,
                            Name = "User41",
                            Password = "$2a$11$Qyw4ygMP6Bta3wv2HVR6feni8vS/RKbBYNCgfFW7yharXwOPUAHpW"
                        },
                        new
                        {
                            Id = new Guid("d1a771b4-2db2-44d0-bb46-d15e53b8ffdc"),
                            Email = "user42@example.com",
                            Gender = 0,
                            Name = "User42",
                            Password = "$2a$11$XLpCd0oOxJDQ6Yky.ulXse8zqhq6vPjbvklzmLOJIl2L07qux7FiO"
                        },
                        new
                        {
                            Id = new Guid("7d720cd9-584d-456f-9900-17be2be0f4ab"),
                            Email = "user43@example.com",
                            Gender = 1,
                            Name = "User43",
                            Password = "$2a$11$Ee.AtpIqWVrczP2Ti8qo5O/xg5zXe1KshNSYesjJNC1xmAsWbZdx2"
                        },
                        new
                        {
                            Id = new Guid("eb7b4660-6b58-4873-aff9-56946923f0af"),
                            Email = "user44@example.com",
                            Gender = 0,
                            Name = "User44",
                            Password = "$2a$11$qRCaW8UiOPkWxOom/Uk6OO/nZF.xbAI30qEnjUUev.UPPQTJbPAvK"
                        },
                        new
                        {
                            Id = new Guid("c1b0b276-461f-40cd-8d1c-4746f2afc943"),
                            Email = "user45@example.com",
                            Gender = 1,
                            Name = "User45",
                            Password = "$2a$11$MxEEEVNcpl7Vh.otxvf1Cu2hhIxu6ZMYD9s1tFL9v/a9iJUETWy1G"
                        },
                        new
                        {
                            Id = new Guid("3a29e92e-268a-4fd7-98d1-b805112825b8"),
                            Email = "user46@example.com",
                            Gender = 0,
                            Name = "User46",
                            Password = "$2a$11$kGm8sorK9hsXu4WbSsIrAuoj8.6OXZiGapCCUKzdahoMWyK7c3Pya"
                        },
                        new
                        {
                            Id = new Guid("05a7d2d1-298b-4037-9a7d-97ff1964103c"),
                            Email = "user47@example.com",
                            Gender = 1,
                            Name = "User47",
                            Password = "$2a$11$BAzmau8cO2JjZJIthveCX.xcilR4WOErsjv/bfL6pRf.z8vMTP20q"
                        },
                        new
                        {
                            Id = new Guid("aa3de1e0-9e51-405e-8d22-0fde889cf9a5"),
                            Email = "user48@example.com",
                            Gender = 0,
                            Name = "User48",
                            Password = "$2a$11$69es8jsyk.FfV5tcmmzmzerAeIlK6gv9PHlShedOtLil9ZXAF9PzW"
                        },
                        new
                        {
                            Id = new Guid("c85964dd-4dda-4109-9302-a4847b25b9c2"),
                            Email = "user49@example.com",
                            Gender = 1,
                            Name = "User49",
                            Password = "$2a$11$aNfkJBSupkTy9NuJ7LOt3uhlixY8B.lC.eaTyTnyOXMZX/VLNBe.K"
                        },
                        new
                        {
                            Id = new Guid("35ad2725-3e8a-43b0-826d-aee94c652e9b"),
                            Email = "user50@example.com",
                            Gender = 0,
                            Name = "User50",
                            Password = "$2a$11$TUQi5xt/Pri01FBienEeR.PsWMElzCGGrSCb6DCyB8bH8HCxLHDL6"
                        },
                        new
                        {
                            Id = new Guid("048ce841-8e1f-4920-ad33-b2c73f37481e"),
                            Email = "user51@example.com",
                            Gender = 1,
                            Name = "User51",
                            Password = "$2a$11$Vwl7tI3dogQkN2du1lz.du4f/3RHj/FasxSfh0L0T5kLPZcFMXA8i"
                        },
                        new
                        {
                            Id = new Guid("2e037cfb-cf6e-4def-8ece-69839d9fa57b"),
                            Email = "user52@example.com",
                            Gender = 0,
                            Name = "User52",
                            Password = "$2a$11$3KIHhaz8WbDC16jWMRHjLe8lTF9BDCKAqoeHxEbvLMRX7vpufpWDO"
                        },
                        new
                        {
                            Id = new Guid("0062ebc0-6a55-40c6-bc17-8b637606802b"),
                            Email = "user53@example.com",
                            Gender = 1,
                            Name = "User53",
                            Password = "$2a$11$CLjN0t2ZOTxvo4zDwn6yzus7BsC2YOCFRF/LnwZw47FCcrutuYa4."
                        },
                        new
                        {
                            Id = new Guid("b1b12b7c-04fc-44b9-8e85-6200490848c2"),
                            Email = "user54@example.com",
                            Gender = 0,
                            Name = "User54",
                            Password = "$2a$11$QZZ2VbbZVl.dI1yefAQmR.GH.4P8w1Bw6ef.aI3tkoBCszOp4Orle"
                        },
                        new
                        {
                            Id = new Guid("03d0c348-05c1-46c0-8436-ee909b867986"),
                            Email = "user55@example.com",
                            Gender = 1,
                            Name = "User55",
                            Password = "$2a$11$x36/2R2Iu10.2WkN8JQ7NeidbhX7DVuVQ4SVcA4NcjhBVEbGho3nu"
                        },
                        new
                        {
                            Id = new Guid("e09d7938-7b33-49b7-bcd5-e58659c05477"),
                            Email = "user56@example.com",
                            Gender = 0,
                            Name = "User56",
                            Password = "$2a$11$p1qwA/5uwZF5xhi6Gb08iuI0q.kQsIMhnJphQNefxchtkPlDPVFRK"
                        },
                        new
                        {
                            Id = new Guid("1453afb3-acc5-4450-97c6-1d429c139c44"),
                            Email = "user57@example.com",
                            Gender = 1,
                            Name = "User57",
                            Password = "$2a$11$IPXktBMuvhJW2/xkGEyPVuXA.TrciwlnKS5lMxf.iihH/Sz38V2Ka"
                        },
                        new
                        {
                            Id = new Guid("1d5a4192-4e0c-42f4-9e71-2ae9ac920157"),
                            Email = "user58@example.com",
                            Gender = 0,
                            Name = "User58",
                            Password = "$2a$11$eYi0kaM25DnNfcwgLMk7oOoW/QiSVNnuZqsK2tiMBs8BQLQTMFF9S"
                        },
                        new
                        {
                            Id = new Guid("f89c5788-754e-4b3a-bec4-62426a231d92"),
                            Email = "user59@example.com",
                            Gender = 1,
                            Name = "User59",
                            Password = "$2a$11$2fkJ8YT0N8gMsZbgc4BjVu/F1BtyiWH4lc4V8b3ukf02nsTp8uXtC"
                        },
                        new
                        {
                            Id = new Guid("50d9194b-d37a-49d6-b740-07686bee4f58"),
                            Email = "user60@example.com",
                            Gender = 0,
                            Name = "User60",
                            Password = "$2a$11$yebaFsyCb9laSCN5k9.AL.AezrmZ3XDWd2Tj18Rimn1Zxq4N3LbP6"
                        },
                        new
                        {
                            Id = new Guid("4a72700e-1b8e-43f4-8771-329d8dbad9d4"),
                            Email = "user61@example.com",
                            Gender = 1,
                            Name = "User61",
                            Password = "$2a$11$C9W66le5U/fzqZLnANOOFuC5/QlcSkT9lX.xTRRYBQWVvKVNsfyH6"
                        },
                        new
                        {
                            Id = new Guid("e30c40e3-4ddf-43e7-9a99-db71f9719f48"),
                            Email = "user62@example.com",
                            Gender = 0,
                            Name = "User62",
                            Password = "$2a$11$N7HpOFPZuJFEMEsKEi5e3u3/7lYlR9.42WlWkf3Ld9tvIE1ydenMu"
                        },
                        new
                        {
                            Id = new Guid("35a74d04-b7d1-4666-8cb4-8c2a2626a1c3"),
                            Email = "user63@example.com",
                            Gender = 1,
                            Name = "User63",
                            Password = "$2a$11$yhqB3omF0Ht7zM2pkHU5seP4P0JjL8LRWchasKpcjcfHQb32QFPAS"
                        },
                        new
                        {
                            Id = new Guid("41f2b629-08a5-4f2b-807b-7ff693a55826"),
                            Email = "user64@example.com",
                            Gender = 0,
                            Name = "User64",
                            Password = "$2a$11$BowW37dpXTe8WyqacAH8puqCdL/ikNAMZxKUfiJbqLfTpFrkVoa0m"
                        },
                        new
                        {
                            Id = new Guid("78dfb8ca-17c4-41f0-8bcf-32d1ddc1852e"),
                            Email = "user65@example.com",
                            Gender = 1,
                            Name = "User65",
                            Password = "$2a$11$83Z3jv/LZyqIqa7zhjaMm.MsBuWefJurcvkZxJ50SP52ufmaHt9ti"
                        },
                        new
                        {
                            Id = new Guid("2dfa4903-5e71-4313-8973-308f4c548f29"),
                            Email = "user66@example.com",
                            Gender = 0,
                            Name = "User66",
                            Password = "$2a$11$OXzAVZA4mRYeMuE5Ye6DMu6UzyTIMEqL.popTQGu6MarTahtu..dq"
                        },
                        new
                        {
                            Id = new Guid("67e8aae7-4472-45ef-a7b7-44d917479b41"),
                            Email = "user67@example.com",
                            Gender = 1,
                            Name = "User67",
                            Password = "$2a$11$cNPEVTjFdgbWaXFG8b9R9Ou3wJwUYrv58jj7AiQD0LG6vwG0WeGMq"
                        },
                        new
                        {
                            Id = new Guid("487b7ea9-c187-4b95-8abf-81825d0b0d40"),
                            Email = "user68@example.com",
                            Gender = 0,
                            Name = "User68",
                            Password = "$2a$11$JgSnH.oQQGfr0V/KpZpnDOzk5F7edHoeD.GmVdrKBH4am40sXnXsK"
                        },
                        new
                        {
                            Id = new Guid("4e0556e5-5718-4c34-9267-787580fc5e72"),
                            Email = "user69@example.com",
                            Gender = 1,
                            Name = "User69",
                            Password = "$2a$11$7oEeVBYhWTdBjDvSKIAoJuQ5BEA6sTV0hbdFEwp6RWvetkKnCIvz6"
                        },
                        new
                        {
                            Id = new Guid("24ef338e-856c-43f6-ba20-4f915302e570"),
                            Email = "user70@example.com",
                            Gender = 0,
                            Name = "User70",
                            Password = "$2a$11$19rLAgkVy1KKdU0d75PbcuVivtumX.MVkSq1cPMC4ALpFBUo8q6.u"
                        },
                        new
                        {
                            Id = new Guid("e2a71446-03fd-4d0f-94e7-d254e5343293"),
                            Email = "user71@example.com",
                            Gender = 1,
                            Name = "User71",
                            Password = "$2a$11$gYiBct.CKrraSOo2nwzY2.EWt2Ljhg01cRirapsBaPpt8Wk//6ene"
                        },
                        new
                        {
                            Id = new Guid("36d19dcf-027e-4062-9ab3-84ecc9473163"),
                            Email = "user72@example.com",
                            Gender = 0,
                            Name = "User72",
                            Password = "$2a$11$5fXZBt.SyXVPhl.SyTH3ZeU93KAkKb9ikrI/nE6MLcvgcYI92EuXC"
                        },
                        new
                        {
                            Id = new Guid("a19c05cb-1309-4067-a5b9-18df99f7e2b2"),
                            Email = "user73@example.com",
                            Gender = 1,
                            Name = "User73",
                            Password = "$2a$11$YG3RdJFOTM6ynHqk8T9CauXx.qW3b9upB.IhEFKRqAnSitTFEHD8C"
                        },
                        new
                        {
                            Id = new Guid("31b670f1-51ed-4c31-ac0f-03ffc4b25395"),
                            Email = "user74@example.com",
                            Gender = 0,
                            Name = "User74",
                            Password = "$2a$11$WeNWCrq0ixkDCvrPYumJy.gqv4WGApRIWE5xZ4T64SkYD/vuo8Pfy"
                        },
                        new
                        {
                            Id = new Guid("0f342f9e-e39f-42b8-b60b-d07ec811b2aa"),
                            Email = "user75@example.com",
                            Gender = 1,
                            Name = "User75",
                            Password = "$2a$11$k5nnF223p43LPgT9Mpph9eZN5qKx5pAX1oTN/.ifbzX1YNYTTjsVG"
                        },
                        new
                        {
                            Id = new Guid("899a776b-e1d9-4cb3-a951-fdd2c477a871"),
                            Email = "user76@example.com",
                            Gender = 0,
                            Name = "User76",
                            Password = "$2a$11$iegZDXqacNn97Z5KYwI/OeuzZlZVMne5XavPVQi.8I3jEOghu/ADC"
                        },
                        new
                        {
                            Id = new Guid("376447ee-9c9a-433b-8c1d-2f852c6d8db1"),
                            Email = "user77@example.com",
                            Gender = 1,
                            Name = "User77",
                            Password = "$2a$11$dZLiwgiX5ofoE.i.d06bNO9Qb9BmJjmaFwaDhMY7kK.0YK/aHHBiW"
                        },
                        new
                        {
                            Id = new Guid("082cf2ff-9a2f-4893-b73b-f42999a2ac99"),
                            Email = "user78@example.com",
                            Gender = 0,
                            Name = "User78",
                            Password = "$2a$11$kxtjZLJmA7oSCM9HvmRppuuhXlxjtUCrgI6V9HFuYt0NvCXrmRjR6"
                        },
                        new
                        {
                            Id = new Guid("33652314-82a5-43d0-b62c-f0dc0e26a8d0"),
                            Email = "user79@example.com",
                            Gender = 1,
                            Name = "User79",
                            Password = "$2a$11$/sIojQkHLrlLYDHq2W9N8.ICBT7aK89qIrBJwDO5YZn09rXS9IKoG"
                        },
                        new
                        {
                            Id = new Guid("4d1f0e58-1643-4ab5-af89-95dc0b2f0539"),
                            Email = "user80@example.com",
                            Gender = 0,
                            Name = "User80",
                            Password = "$2a$11$esAlKpqpTChIYEUDnVl9jOB8V4bEPv7.Fz/JAlOJQNiZdElPfYUf2"
                        },
                        new
                        {
                            Id = new Guid("f51844af-a9fa-42e9-aa39-4708de91ac3d"),
                            Email = "user81@example.com",
                            Gender = 1,
                            Name = "User81",
                            Password = "$2a$11$u7FEvAPNClOWZvZ8NXBUdeAOQPX6yob6CtmGNVuqDgVwIKURfySvy"
                        },
                        new
                        {
                            Id = new Guid("59255312-aa0c-4ae9-8d0c-9cbc43e30a4f"),
                            Email = "user82@example.com",
                            Gender = 0,
                            Name = "User82",
                            Password = "$2a$11$OsMwGqOZ8t/203/l6smGvOM6LTwRaMfOioPhn490qt0ztxAK4blua"
                        },
                        new
                        {
                            Id = new Guid("7b37bd1f-fcc0-4987-a482-2d576cc6a912"),
                            Email = "user83@example.com",
                            Gender = 1,
                            Name = "User83",
                            Password = "$2a$11$pAxrO0IYxIFcpozJfu67meQAC8HmMaU97YijwVwCfGN8EnyHSm306"
                        },
                        new
                        {
                            Id = new Guid("9e9b8b13-969c-4378-8921-88a499085af6"),
                            Email = "user84@example.com",
                            Gender = 0,
                            Name = "User84",
                            Password = "$2a$11$48v6zYgnB1V7jPjeZ2hk4u4MNHQZRDhe521dRUjMZoRmsDGj3dU3m"
                        },
                        new
                        {
                            Id = new Guid("9f0d96d2-2fbc-49a4-9ad1-c4f911ed2094"),
                            Email = "user85@example.com",
                            Gender = 1,
                            Name = "User85",
                            Password = "$2a$11$PxGOoaI/oroEkLrC.7mv2enK.xvq3Cq9uvz6OkrhQk9VAC1DjmJF2"
                        },
                        new
                        {
                            Id = new Guid("e4421306-7fb1-45fe-b0ae-67c93282cf1d"),
                            Email = "user86@example.com",
                            Gender = 0,
                            Name = "User86",
                            Password = "$2a$11$8L6Yh8p3YeyohY9oK0c8KO3w9P057erXr0FK5xHUZnqVslinc8KtC"
                        },
                        new
                        {
                            Id = new Guid("eff3c3bd-519d-4d1c-adac-62d3d4020f7e"),
                            Email = "user87@example.com",
                            Gender = 1,
                            Name = "User87",
                            Password = "$2a$11$FBYub4Q5ONgSM/e9ihiRw./pMRF0VY.7BBqgFdIu19bhabn7GfaH."
                        },
                        new
                        {
                            Id = new Guid("6b9f4bd2-531e-43bf-a8b6-fd085b4cef0c"),
                            Email = "user88@example.com",
                            Gender = 0,
                            Name = "User88",
                            Password = "$2a$11$qm13Z8R2ocynV7q8xPyIcOqlygVLgouE/HDu8a4DavPU4X1aLcb96"
                        },
                        new
                        {
                            Id = new Guid("ebb7f294-5a1e-407c-9326-250d54e28420"),
                            Email = "user89@example.com",
                            Gender = 1,
                            Name = "User89",
                            Password = "$2a$11$1yIAR7xgDbHQCiK8osU4QOTzgwmznBKpn3SbFNwXSvdgAzumbWsfG"
                        },
                        new
                        {
                            Id = new Guid("17c3bd48-27b6-431c-82e5-2241353b2cb3"),
                            Email = "user90@example.com",
                            Gender = 0,
                            Name = "User90",
                            Password = "$2a$11$vcJhO7NBkolPs3gBRf3VhuD34KitQRMpgLbzEq59OEHILAur6EnXa"
                        },
                        new
                        {
                            Id = new Guid("ba42f8c7-6ddf-49de-add7-1ca800fa0819"),
                            Email = "user91@example.com",
                            Gender = 1,
                            Name = "User91",
                            Password = "$2a$11$kc07RqqYkcop7FpeA6fKnutnfwf6DPXs79iWMa0LBZNfdyGcBoAz6"
                        },
                        new
                        {
                            Id = new Guid("f5f7d93e-fe3b-45a7-ac3c-33f4eea6c413"),
                            Email = "user92@example.com",
                            Gender = 0,
                            Name = "User92",
                            Password = "$2a$11$0EsgFf8rWs1rd1YGwt0i7eSg8F9TJzsJUc15Dd9V8QYwJ6yUElzAG"
                        },
                        new
                        {
                            Id = new Guid("192791a8-eddd-42a6-92c4-db1b1a1c4185"),
                            Email = "user93@example.com",
                            Gender = 1,
                            Name = "User93",
                            Password = "$2a$11$ZXWyHF1gsIB7099AqvHVq.bVtAmLt3Dg.90raVuESnxArttY1WdTS"
                        },
                        new
                        {
                            Id = new Guid("9f83adbb-10d2-422f-9a01-4a1984599190"),
                            Email = "user94@example.com",
                            Gender = 0,
                            Name = "User94",
                            Password = "$2a$11$ftSFeDkOHJ6Lzgv3/ZNSuuSbV9gZyNBBvc3OlqP/8Adr5iFx65znG"
                        },
                        new
                        {
                            Id = new Guid("c81d6c63-b1da-47e0-8cc6-ea7f4eefb634"),
                            Email = "user95@example.com",
                            Gender = 1,
                            Name = "User95",
                            Password = "$2a$11$DyqkcQr78sVkwMCwSoq0qOxuuGcEvxtpRsrLPO/Ar5l0N2VcPRP2u"
                        },
                        new
                        {
                            Id = new Guid("668a4de0-c88e-4aa4-bdb4-61a620ae39be"),
                            Email = "user96@example.com",
                            Gender = 0,
                            Name = "User96",
                            Password = "$2a$11$ebLWkTZ4Ee07Gw8PJze0qe6u3ryyshQWK2dLnOyg4IzTzyCQ2tZV."
                        },
                        new
                        {
                            Id = new Guid("04c1bf20-54a3-4667-b1de-cf198424a5db"),
                            Email = "user97@example.com",
                            Gender = 1,
                            Name = "User97",
                            Password = "$2a$11$CLSVgO5L8YFnQwoh4QRbt.ICF3vuywAqsTBauklTo1VJzBoaeVbHC"
                        },
                        new
                        {
                            Id = new Guid("38450798-b67a-4651-9f21-dd2f71a04fbc"),
                            Email = "user98@example.com",
                            Gender = 0,
                            Name = "User98",
                            Password = "$2a$11$t37NJru/cS3nswkhFHKV0eLrY13HuvADczsi5l5I9XPYJD3FHUqWy"
                        },
                        new
                        {
                            Id = new Guid("2296497b-9071-4268-a2c0-9718e95425fe"),
                            Email = "user99@example.com",
                            Gender = 1,
                            Name = "User99",
                            Password = "$2a$11$JKrHD1dWmNLUSYbOOTZlkedxk2hypA6RoJ5ElzMp2gM5Vh1tP8ECu"
                        },
                        new
                        {
                            Id = new Guid("47a4bb3b-d961-43bf-93f6-f77a6ffcd297"),
                            Email = "user100@example.com",
                            Gender = 0,
                            Name = "User100",
                            Password = "$2a$11$jUwU9aMexNOhR4q8LYRFnePizmld5OZxCl7x9leh60IQ/GvNtEs7m"
                        });
                });

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.HasOne("PassSystemTD.Entities.User", "User")
                        .WithMany("Passes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Proof", b =>
                {
                    b.HasOne("PassSystemTD.Entities.Pass", "Pass")
                        .WithMany("Proofs")
                        .HasForeignKey("PassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Role", b =>
                {
                    b.HasOne("PassSystemTD.Entities.User", "User")
                        .WithOne("Role")
                        .HasForeignKey("PassSystemTD.Entities.Role", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("PassSystemTD.Entities.User", b =>
                {
                    b.Navigation("Passes");

                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
