// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PassSystemTD.Data;

#nullable disable

namespace PassSystemTD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250307142235_FixedRoleAgain3")]
    partial class FixedRoleAgain3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PassStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Proof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PassId");

                    b.ToTable("Proofs");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDean")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47c8ef3a-0ecf-4255-9be9-fc3b673c1d4e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("2027db61-452c-4bf5-8f34-493c93ddf9bf")
                        },
                        new
                        {
                            Id = new Guid("5634557f-812a-4f91-82ed-0fc96aa28dc2"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("69af8236-db70-4c6a-b7f7-e4625e779313")
                        },
                        new
                        {
                            Id = new Guid("8e83f7d9-d9cd-4d5c-be61-dfa30c4de329"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("7bf90894-1d33-4b21-aa74-b88e6c7c244d")
                        },
                        new
                        {
                            Id = new Guid("fed3d554-653e-4a5e-a117-b9f2274edba8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("cdc515c0-6b42-4494-a936-bbbf0193ee80")
                        },
                        new
                        {
                            Id = new Guid("9ca74fa8-482f-497a-8caf-20d501ec93cd"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("eb6abea0-0e79-4216-8c29-38d3e0c23d77")
                        },
                        new
                        {
                            Id = new Guid("993e94cd-775b-4657-b8e0-68e1e48ff0db"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("3bdc1960-13b5-42d4-8618-0c2e52d72721")
                        },
                        new
                        {
                            Id = new Guid("b49a4d03-69e3-4a0e-a836-278677518123"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("e83d3398-ad83-468a-96c8-2b071ab4159e")
                        },
                        new
                        {
                            Id = new Guid("813b32d4-4004-4df5-9671-1fd0410cfe93"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("e719a908-f784-42c6-bb49-ee71649a442b")
                        },
                        new
                        {
                            Id = new Guid("1646abc4-5060-4684-807c-28695e9ba9c1"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("d5933118-eb16-4391-be5a-d4f726b1bbae")
                        },
                        new
                        {
                            Id = new Guid("0e856a15-73d8-4948-ad68-b3e8155cd501"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("5d1cc15c-b3e1-413b-9314-7933a5bed49b")
                        },
                        new
                        {
                            Id = new Guid("2ff20b14-f52d-46c2-994a-8b06f48a4802"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("1b271e5d-f143-433c-9909-18304784c0dc")
                        },
                        new
                        {
                            Id = new Guid("0ef255ee-5523-419e-9d7e-33b5ff92c0bd"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("5155113f-466d-4f00-93b8-e75b6c8f7189")
                        },
                        new
                        {
                            Id = new Guid("5fdeb301-a27e-4a07-ae26-e8f777f4c7b1"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("b31e5d44-8ed3-479a-b6d6-59f632630ab0")
                        },
                        new
                        {
                            Id = new Guid("2eac3628-02be-452a-bded-39cb31454006"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("33b3d7ed-c116-4351-ad2e-ae1b6bc1cd95")
                        },
                        new
                        {
                            Id = new Guid("56806919-9512-479b-afdb-7d80220cefdd"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true,
                            UserId = new Guid("9ac52ade-a530-4447-83c4-dbf15d463f17")
                        },
                        new
                        {
                            Id = new Guid("d73fbeb5-c0b9-460a-8cf0-f741fec099e8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("0641a5ea-d749-4991-a982-330252578fae")
                        },
                        new
                        {
                            Id = new Guid("be9de5da-e339-4968-85dc-032121ed74b2"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("8533808b-75cb-448c-89a4-666b476c9f2a")
                        },
                        new
                        {
                            Id = new Guid("a2ef0935-5f4c-4820-9d43-361bea11a096"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("8abb5551-1228-4c96-9300-949f91ec7b33")
                        },
                        new
                        {
                            Id = new Guid("eec886f4-a9db-48bc-b0e8-e6b657970778"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("e54eeb7c-ba03-4123-bdb8-3c2bc61211b5")
                        },
                        new
                        {
                            Id = new Guid("b4da5b75-14a2-49ba-bd56-f662e783e632"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("e77e4678-de32-42bf-bce4-097956c07c8c")
                        },
                        new
                        {
                            Id = new Guid("97d72995-1f24-4631-a8eb-1eab1385d04a"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("2563db6f-4c4e-4031-b41a-850a1b243181")
                        },
                        new
                        {
                            Id = new Guid("4caa40ae-1827-4a65-bde7-f05c949a7bc3"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("7491c501-478a-4aeb-ae00-17ac630e1314")
                        },
                        new
                        {
                            Id = new Guid("9b8e4f52-1db6-407c-8cf1-3397e79f1253"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("5144ae96-d3bb-4199-a7a0-342774f16bf6")
                        },
                        new
                        {
                            Id = new Guid("3034079b-ffd4-4f97-a9fa-699d62795b2b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("66d1eafb-4e91-4d1b-a102-9ccbcba4253a")
                        },
                        new
                        {
                            Id = new Guid("83d3c4a1-465a-4beb-910f-336afb2301e1"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("b9f39656-a26d-45a3-8a09-ee9c162bc11d")
                        },
                        new
                        {
                            Id = new Guid("ef258e22-8e0c-478d-b963-3be1921ecc47"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("62d062ea-4100-4138-bd9f-6e7a1fcf9dd8")
                        },
                        new
                        {
                            Id = new Guid("18e83c78-812c-4de7-98ee-d751c6460f78"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("68aa8b00-622e-44fc-9f98-25b3c9c23f34")
                        },
                        new
                        {
                            Id = new Guid("ffd42a30-e582-4df8-9208-ff5fdef33d28"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("c6d64e0a-e373-437f-8fcd-0d83228f7c44")
                        },
                        new
                        {
                            Id = new Guid("44339d22-f4d3-4117-9e8e-7007a6638f41"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("480bf0d9-39d6-4fd3-9b1e-ad138aeb3483")
                        },
                        new
                        {
                            Id = new Guid("01522160-a509-4659-aa80-772b0c50d501"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true,
                            UserId = new Guid("3f0f7602-7055-4a5d-8aa7-a3d25c7d6ede")
                        },
                        new
                        {
                            Id = new Guid("1c0972ff-3d9b-482f-8b36-93cda5f73123"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("9d795ca6-def5-47ee-9a66-9605eabc97ca")
                        },
                        new
                        {
                            Id = new Guid("13efeb92-5001-413d-8d00-4ba5a1d8cbf5"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("860c31a6-78c2-4886-941c-be174fd55a89")
                        },
                        new
                        {
                            Id = new Guid("2d99793c-4a6c-4e13-9c44-dd0323ec3f17"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("21f9b2cf-b6ef-4d11-a0ba-818d26d7a006")
                        },
                        new
                        {
                            Id = new Guid("e22d0f9a-1061-4d24-a669-acc8931d7023"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("883f74e0-5e1a-4a79-861a-ecb314a07fba")
                        },
                        new
                        {
                            Id = new Guid("cd05b1b6-9ec2-443e-b946-619c6d0919d2"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("2c4dd255-2a45-45f8-ae1f-fc8851d3782a")
                        },
                        new
                        {
                            Id = new Guid("fe0099d2-f62f-4151-8c89-9aac0d32e78f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("9f33c46b-4abd-4fd9-bc83-7b7f9f74c491")
                        },
                        new
                        {
                            Id = new Guid("ec8f5aca-9b03-4b5d-a633-6ea6711aa0f8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("7263f1f1-a731-40e0-a94a-e96eab6424a6")
                        },
                        new
                        {
                            Id = new Guid("bd40ae06-825a-4b7e-a9de-e2aaf2cae4a7"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("8815dd6f-0311-4e85-b233-985960745df6")
                        },
                        new
                        {
                            Id = new Guid("11839a6b-ba09-492e-8d74-019d07b9bbaf"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("2215e8fb-a6f5-4b37-8b50-7a6b02d581d6")
                        },
                        new
                        {
                            Id = new Guid("b3dbd91a-6673-49a8-9a05-44783b5f7411"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("8b6b979d-a208-4c2e-8815-caa546dee237")
                        },
                        new
                        {
                            Id = new Guid("f68e256b-ee49-4326-8ac6-9f83d7af001b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("49a9aae9-2b91-4812-a7d2-c96d7a2cb973")
                        },
                        new
                        {
                            Id = new Guid("087a9dff-7477-43cd-a394-069be95ca989"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("fa737043-6a38-4793-a8b8-de4fa410862a")
                        },
                        new
                        {
                            Id = new Guid("6b18a096-62a9-4a7c-b5d1-3c0c66093108"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("cc196503-7307-4280-a8f7-42bbca4f8c24")
                        },
                        new
                        {
                            Id = new Guid("a087980a-726e-410e-8902-dd2bc051e255"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("b01b7f37-433b-4529-94d0-3644ef9724e9")
                        },
                        new
                        {
                            Id = new Guid("74750442-13a9-431d-a990-fbb18dcc7654"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true,
                            UserId = new Guid("6bbdefc6-358d-4a57-9fea-4ac4d31cf0df")
                        },
                        new
                        {
                            Id = new Guid("b5b04b06-71f4-4adc-bc71-958600532281"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("8c8d2905-6abf-456e-9044-81c184b4d223")
                        },
                        new
                        {
                            Id = new Guid("94302913-78fc-4940-9754-47e7c0aa2429"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("740a0023-5020-430b-abf7-39b8b24a398e")
                        },
                        new
                        {
                            Id = new Guid("e8fed88a-aa3f-4144-94c0-b174005f384f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("86a09aca-ead3-4708-916e-38f6f293236d")
                        },
                        new
                        {
                            Id = new Guid("efb280af-8b30-47af-ab12-fa9c09b526b1"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("28223e42-61a3-4d19-a48a-46296a43de79")
                        },
                        new
                        {
                            Id = new Guid("7a94b568-38eb-411d-9dd6-d337f7779053"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("9e5e4896-b923-4cd9-841c-77fa1fe6537a")
                        },
                        new
                        {
                            Id = new Guid("49984aaa-b2ab-46ac-8a18-51e0590020af"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("1f50e98b-1acd-432c-8d6c-49e5f94ec654")
                        },
                        new
                        {
                            Id = new Guid("84e862ce-f4c5-4fc7-823a-8ff2a8779f66"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("78e58e86-5e6c-4c00-add1-739b665768cc")
                        },
                        new
                        {
                            Id = new Guid("9e39fedf-bc1b-4350-83c5-2eebea877644"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("84c17fb7-3997-4eb9-bcbe-02a606f6ea56")
                        },
                        new
                        {
                            Id = new Guid("d81add96-959f-4c94-9fad-d64066249bfa"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("93d265cd-a39f-4cce-b97f-ed5b031eee35")
                        },
                        new
                        {
                            Id = new Guid("0c42d1b0-068a-4891-84f2-a825a3b95c48"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("2e89e813-5a6a-41c3-8893-190a31ef8bd5")
                        },
                        new
                        {
                            Id = new Guid("61d3b18b-2db2-47aa-a9cb-011fe0fdc50d"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("2d3ec0d3-130b-4bd7-8202-f57387412d69")
                        },
                        new
                        {
                            Id = new Guid("1240c8af-580d-4cb9-92e5-5d93890040c3"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("145b1d2f-1da3-4bec-a978-539a332c1649")
                        },
                        new
                        {
                            Id = new Guid("1d3c765b-d720-4bcc-a606-c5bffcc4bc31"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("1e67b20a-c523-4178-bdf5-16d452781b27")
                        },
                        new
                        {
                            Id = new Guid("17f2b2ac-0f2c-45dd-a85a-7a8abe0d7be8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("2471054b-a45e-44fd-86d9-2af2f6345793")
                        },
                        new
                        {
                            Id = new Guid("8ac0f1ed-7f7b-4c8a-aeab-e60a9be034ae"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true,
                            UserId = new Guid("0c77ee4c-b8d6-454e-978e-be2257dd2e3c")
                        },
                        new
                        {
                            Id = new Guid("ef509d7a-437f-4de9-b664-dc97cd82b0db"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("3dfce0b1-7d61-47ff-9053-1b18a3a9a69a")
                        },
                        new
                        {
                            Id = new Guid("3bff0d9b-5aab-4c6f-be00-3d8bbf85189c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("0f2c23ef-8e11-4f85-85ba-78ccd150d9bb")
                        },
                        new
                        {
                            Id = new Guid("207dd016-39e0-4b13-944f-4cb0e189f848"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("4506f837-d214-48bb-8a71-5faea5494c83")
                        },
                        new
                        {
                            Id = new Guid("085b2acc-dc89-4433-baa9-a89b94d54639"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("a5966ef9-31ea-4e17-b5f3-bfcc2920297d")
                        },
                        new
                        {
                            Id = new Guid("37a40bf2-8808-43d5-9e2a-210a526015f4"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("5312113a-ce17-476f-bf87-5e3a861027c2")
                        },
                        new
                        {
                            Id = new Guid("b6aa6019-27da-40a2-816e-92a148f47140"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("7897a73e-7546-498d-bde6-4f0a8abdd24d")
                        },
                        new
                        {
                            Id = new Guid("1fe40b16-0c97-4294-aed6-f8e9aaa3790a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("e4100d6d-dd3a-4a08-9206-fba2e9e9e536")
                        },
                        new
                        {
                            Id = new Guid("ee63961c-a1d4-4183-bdcd-642b7fc63c89"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("bc16147c-3863-483f-ab18-cfbdb91166d8")
                        },
                        new
                        {
                            Id = new Guid("c41f7070-f624-4cf2-a434-6c93d216820b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("a521b155-dc28-4c92-bf3d-1ce2b745f892")
                        },
                        new
                        {
                            Id = new Guid("441de618-14cb-4bdb-b6a2-ba532bd86630"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("3e546a14-ccb5-4e75-92f5-c1f3614953a5")
                        },
                        new
                        {
                            Id = new Guid("1013b788-fda6-499e-8972-030a53f128ad"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("ce52fca6-72d1-4d97-a529-401a09648b9d")
                        },
                        new
                        {
                            Id = new Guid("856e062c-456e-43d3-8398-81503db4c994"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("8a6ee593-0716-4ecb-96a5-ecfe1ea596c9")
                        },
                        new
                        {
                            Id = new Guid("dbb2e333-d8f0-4e9b-94d1-9e7ea9c2b662"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("b30cbdab-d85f-441f-8859-e9588cd6527f")
                        },
                        new
                        {
                            Id = new Guid("851b5fe2-7847-48db-ab15-8e5734142496"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("8554f8f0-8c01-4ea7-9982-d9696e59f5d7")
                        },
                        new
                        {
                            Id = new Guid("9c17168e-6b19-40df-b95c-790733cb6e45"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true,
                            UserId = new Guid("0abe5794-e3d6-4950-a75e-3d83ed9f022b")
                        },
                        new
                        {
                            Id = new Guid("2b91d631-e3c3-44ab-90e2-4ba37e721797"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("b54be218-f3ed-44f0-a88c-8e3362a2f9a1")
                        },
                        new
                        {
                            Id = new Guid("5b575eae-9b11-4842-b6e7-c6f2aeca6be9"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("30e1d0f3-ccae-4785-ae51-52e6c994aacd")
                        },
                        new
                        {
                            Id = new Guid("9fc781ab-0d0c-42f9-9208-9c729cdf093f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("da2a8d35-b8b4-4679-b0fb-f33cfe973459")
                        },
                        new
                        {
                            Id = new Guid("2070a997-f4a7-4770-a418-81bfd07313dd"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("eda6168b-6515-4b5f-a4ee-6af2a31312f9")
                        },
                        new
                        {
                            Id = new Guid("7bf76e6e-17fd-436a-9f2e-6cd9e2ae76fc"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("731fb401-e0cd-4aee-bf79-7a3fc0e5f69d")
                        },
                        new
                        {
                            Id = new Guid("520587f7-8001-4c2f-ae8f-b4174c10f1e1"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("f97b231c-31da-49a3-90eb-306bef8c72c1")
                        },
                        new
                        {
                            Id = new Guid("6f6ccb1e-d2e8-4c1b-b0c4-8a51a341ff06"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("10148a74-60c6-4888-9f69-70a74945d394")
                        },
                        new
                        {
                            Id = new Guid("ccc1ca2a-ca80-402c-93a7-6da4768920b4"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("4e37bbbb-642e-43f2-83bf-2e70402016a1")
                        },
                        new
                        {
                            Id = new Guid("5aca1cd8-257a-496a-bfe7-07a107ecb718"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("4efa3c17-9aed-4182-9bf6-1e9dce436d13")
                        },
                        new
                        {
                            Id = new Guid("487e258f-a9a4-48af-b6a5-4ed95ce3c473"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("30912a18-6188-4bd7-b266-1bc5a56e0e06")
                        },
                        new
                        {
                            Id = new Guid("162e6092-6bf6-4768-bca8-bbf7a30479d8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("4c682287-c7d1-49bf-8baf-012590d02fff")
                        },
                        new
                        {
                            Id = new Guid("7403d73b-4d89-4c20-b5a8-1077ca33ce9e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("6f77416f-8c2e-455b-82dc-346345f1cc66")
                        },
                        new
                        {
                            Id = new Guid("cf83d198-160b-404c-bc76-63fa93d80f6a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("2292e013-8588-4fac-9676-8582b686d631")
                        },
                        new
                        {
                            Id = new Guid("fc6e35b6-3c07-4e32-b6e1-9f0b7f34675d"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("f75fccc3-92e9-4827-ae42-b6500c968337")
                        },
                        new
                        {
                            Id = new Guid("ba809136-2aee-4c00-bcf4-272f7e472c32"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true,
                            UserId = new Guid("57ef23b1-38f3-41fb-9bf0-c5470eb193a1")
                        },
                        new
                        {
                            Id = new Guid("9861dbce-6a03-427e-a696-7f170bca80bd"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("a13bbaf6-66a3-4087-b7f4-9b5c7e472bb2")
                        },
                        new
                        {
                            Id = new Guid("78e92936-afc5-45f8-84e4-1f716278530e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("50d128ec-ca48-44f3-9248-0d00c4a8cb6c")
                        },
                        new
                        {
                            Id = new Guid("035ea55f-69e8-4daa-b5e7-b0e277862828"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("f5a82c47-1dc2-41cd-9546-8c62b5b08045")
                        },
                        new
                        {
                            Id = new Guid("f05e9441-8dfb-402e-a15e-c2d064e0e68b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("e038d487-a20e-4b00-8777-3730b05a7c67")
                        },
                        new
                        {
                            Id = new Guid("e1fb2018-24d2-4956-aad5-99c44d3c7c26"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("a329d081-971e-43aa-a388-9683e85697e6")
                        },
                        new
                        {
                            Id = new Guid("6a76d9aa-849e-4c68-b218-5898246a6e46"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("992f6210-4e0d-4578-b3c5-e09a02bbdaca")
                        },
                        new
                        {
                            Id = new Guid("0231cee2-5471-4658-b326-0696c17a05f1"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("a957989e-226f-4bb8-afa2-94e6d40998e9")
                        },
                        new
                        {
                            Id = new Guid("00bff54c-20b2-403d-a419-f493aa760737"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false,
                            UserId = new Guid("0fb0c78d-3129-4405-b10f-739deea74b39")
                        },
                        new
                        {
                            Id = new Guid("ccfa113a-e520-4479-9af9-bc2365dd0897"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false,
                            UserId = new Guid("a41982b7-d58c-42ff-942b-31059e50140a")
                        },
                        new
                        {
                            Id = new Guid("a7272a23-9493-412a-8838-d31a6b348058"),
                            IsAdmin = true,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true,
                            UserId = new Guid("7e80f554-4aa0-48f7-84ed-64f60ebd8099")
                        });
                });

            modelBuilder.Entity("PassSystemTD.Entities.TokenEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Token");

                    b.ToTable("BannedTokens");
                });

            modelBuilder.Entity("PassSystemTD.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2027db61-452c-4bf5-8f34-493c93ddf9bf"),
                            Email = "user1@example.com",
                            Gender = 1,
                            Name = "User1",
                            Password = "$2a$11$27o3kFYVIv5WqWd9mD/07OzEeY8p2PLqy3eF7M7DWXZfMeK3aQiii",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("69af8236-db70-4c6a-b7f7-e4625e779313"),
                            Email = "user2@example.com",
                            Gender = 0,
                            Name = "User2",
                            Password = "$2a$11$ClsYGWkrPGks.hes2AzNa.G8dUtpQ/mS35.0YYE2p.Aej2LQWVgiy",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7bf90894-1d33-4b21-aa74-b88e6c7c244d"),
                            Email = "user3@example.com",
                            Gender = 1,
                            Name = "User3",
                            Password = "$2a$11$ulgN2ZWhmFVWVxWtG4nG4eoDiLVvE/VuwQWU7Yn5mASwatoWoJPym",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("cdc515c0-6b42-4494-a936-bbbf0193ee80"),
                            Email = "user4@example.com",
                            Gender = 0,
                            Name = "User4",
                            Password = "$2a$11$cY9oX.knCCU0GNwSNofit.zIoG7uxkcl/aoO9WrFoWD5RTgeEzo8y",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("eb6abea0-0e79-4216-8c29-38d3e0c23d77"),
                            Email = "user5@example.com",
                            Gender = 1,
                            Name = "User5",
                            Password = "$2a$11$/VbpjgbQNaQPrG0Wq.GtHeUl1tVgouHUE95qLbMcdxcDHlTHFDCnK",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3bdc1960-13b5-42d4-8618-0c2e52d72721"),
                            Email = "user6@example.com",
                            Gender = 0,
                            Name = "User6",
                            Password = "$2a$11$i0piMhHWgKqVDYvz96J3kOeYZAoBcoVKkQ1.PIG1PTxs19PtcR.oG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e83d3398-ad83-468a-96c8-2b071ab4159e"),
                            Email = "user7@example.com",
                            Gender = 1,
                            Name = "User7",
                            Password = "$2a$11$OheHEewimKJPuCwIDGSaT.jfdeK8i8/Q6lqHApohmeHTH9HfzzICe",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e719a908-f784-42c6-bb49-ee71649a442b"),
                            Email = "user8@example.com",
                            Gender = 0,
                            Name = "User8",
                            Password = "$2a$11$e3y2ddC2MyZVXPDu0hKvkuZZ0F/Bzl/EGQueUoBT11GAgDY7RMsmG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d5933118-eb16-4391-be5a-d4f726b1bbae"),
                            Email = "user9@example.com",
                            Gender = 1,
                            Name = "User9",
                            Password = "$2a$11$pQvmV/IhPEB1VI3p9vX0I.r1njI9IEmmlDxZTcR4nVZbOrWF2.LiG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5d1cc15c-b3e1-413b-9314-7933a5bed49b"),
                            Email = "user10@example.com",
                            Gender = 0,
                            Name = "User10",
                            Password = "$2a$11$WbbBvVTApsKo/g/YNzHaYe0.b1gW3E2Soa60JJEm3TIA.VbxqI18G",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1b271e5d-f143-433c-9909-18304784c0dc"),
                            Email = "user11@example.com",
                            Gender = 1,
                            Name = "User11",
                            Password = "$2a$11$VCq7dtpX21E4.bK7mfRHUuc/YxYWX0JaF06wQozsWj8zRGYfWeTZi",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5155113f-466d-4f00-93b8-e75b6c8f7189"),
                            Email = "user12@example.com",
                            Gender = 0,
                            Name = "User12",
                            Password = "$2a$11$IVHp0G4vrsTZ5X099UbfcOOMDoX6olRiMnzy151zL9GEhEzT8J462",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b31e5d44-8ed3-479a-b6d6-59f632630ab0"),
                            Email = "user13@example.com",
                            Gender = 1,
                            Name = "User13",
                            Password = "$2a$11$4QLwa1TbF.0qhjPz8bhu6uW.SxuggEzNqlf06amze2I2SOmjud.CC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("33b3d7ed-c116-4351-ad2e-ae1b6bc1cd95"),
                            Email = "user14@example.com",
                            Gender = 0,
                            Name = "User14",
                            Password = "$2a$11$pfy7R1n0/zgXY44nptpxve5Vde9RMZ2jLOnxfK/iQ8nMtjL0d1bkO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9ac52ade-a530-4447-83c4-dbf15d463f17"),
                            Email = "user15@example.com",
                            Gender = 1,
                            Name = "User15",
                            Password = "$2a$11$Z5CfPgDd2fXFDdoC.OOlpuxaKYCE2Qwu33LZJivBJv6HNVOe9H5ii",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0641a5ea-d749-4991-a982-330252578fae"),
                            Email = "user16@example.com",
                            Gender = 0,
                            Name = "User16",
                            Password = "$2a$11$n0JtkeCcHU5/NZiC2rNzVeqXmycz8t7cHQC3XKxjUqi9rhDNjMViG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8533808b-75cb-448c-89a4-666b476c9f2a"),
                            Email = "user17@example.com",
                            Gender = 1,
                            Name = "User17",
                            Password = "$2a$11$2/9NuPOyZ9J8GRhxs5IsrOMbyosIe8l7sclKZ2dDeqRtOZc93J3Iy",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8abb5551-1228-4c96-9300-949f91ec7b33"),
                            Email = "user18@example.com",
                            Gender = 0,
                            Name = "User18",
                            Password = "$2a$11$hvWsty47B//K6sOXRP97FODPZf3IXu2DmcNh0Fw1PwxIjBF0beQSq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e54eeb7c-ba03-4123-bdb8-3c2bc61211b5"),
                            Email = "user19@example.com",
                            Gender = 1,
                            Name = "User19",
                            Password = "$2a$11$aXERz8/JIWMrqJLap5w7curZFbK3lIQPJN36Ns/1sl03.qWhAJuOa",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e77e4678-de32-42bf-bce4-097956c07c8c"),
                            Email = "user20@example.com",
                            Gender = 0,
                            Name = "User20",
                            Password = "$2a$11$cKGZBbmEWjtMIJzkehYwzOd4Xl78J2HkeobOpJ5/dvPLrfhlJcLeC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2563db6f-4c4e-4031-b41a-850a1b243181"),
                            Email = "user21@example.com",
                            Gender = 1,
                            Name = "User21",
                            Password = "$2a$11$wxfeUo7Hd5SW2J3.CfqVGuEtNqfr9PlEu.8eQ/1Qct9ao6ohqs9Ea",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7491c501-478a-4aeb-ae00-17ac630e1314"),
                            Email = "user22@example.com",
                            Gender = 0,
                            Name = "User22",
                            Password = "$2a$11$67Nxxk0rvt6f8F5HXlElAuikDQPQdfPeEbaMnTunRxqrMcZqQfvdS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5144ae96-d3bb-4199-a7a0-342774f16bf6"),
                            Email = "user23@example.com",
                            Gender = 1,
                            Name = "User23",
                            Password = "$2a$11$Tp37Uf7Ebl7OJpaChZGMoeq2.dsZtx7FpltjJ6caJiC3kfeqgmVd6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("66d1eafb-4e91-4d1b-a102-9ccbcba4253a"),
                            Email = "user24@example.com",
                            Gender = 0,
                            Name = "User24",
                            Password = "$2a$11$JXp3spXk3EcRIiQvkz21FOQWDFGVrWxnE/WqZdn6XSaEQZmSpYVwC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b9f39656-a26d-45a3-8a09-ee9c162bc11d"),
                            Email = "user25@example.com",
                            Gender = 1,
                            Name = "User25",
                            Password = "$2a$11$hrhnUhNY3WIyxORL20xeLOxzva99cveQk9OTO3kvb3kVtG3wciFSS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("62d062ea-4100-4138-bd9f-6e7a1fcf9dd8"),
                            Email = "user26@example.com",
                            Gender = 0,
                            Name = "User26",
                            Password = "$2a$11$/tOid/Zg3hPWKjpsAPgNGemVfsdggWT36gvIlLaj2kwaQmScN2GEO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("68aa8b00-622e-44fc-9f98-25b3c9c23f34"),
                            Email = "user27@example.com",
                            Gender = 1,
                            Name = "User27",
                            Password = "$2a$11$xoRoWc1in0GUP1wdUsD2BOxrUd9rYp4ta1yP8QFkSMohFiRB4txMO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c6d64e0a-e373-437f-8fcd-0d83228f7c44"),
                            Email = "user28@example.com",
                            Gender = 0,
                            Name = "User28",
                            Password = "$2a$11$LmnkravZIwwr6VBvHLKW/ODbxCY..br.nXTW5IDxeFkhfcQK8M8Nu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("480bf0d9-39d6-4fd3-9b1e-ad138aeb3483"),
                            Email = "user29@example.com",
                            Gender = 1,
                            Name = "User29",
                            Password = "$2a$11$FziTeKe4hlqFHcakJwnNf.X.2sjeBTvJVUckUAymQ1qIyWgW8dhoe",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3f0f7602-7055-4a5d-8aa7-a3d25c7d6ede"),
                            Email = "user30@example.com",
                            Gender = 0,
                            Name = "User30",
                            Password = "$2a$11$I4hcWCM1tBBl5dychhrs6eziD7tiUbzPh6p5iu6D1vIfVpkGYfz0q",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9d795ca6-def5-47ee-9a66-9605eabc97ca"),
                            Email = "user31@example.com",
                            Gender = 1,
                            Name = "User31",
                            Password = "$2a$11$yt69FGU/EPprfaMXSgclyOkP/9HBfpgQgLlb9GvZfKN70Lmb8b0te",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("860c31a6-78c2-4886-941c-be174fd55a89"),
                            Email = "user32@example.com",
                            Gender = 0,
                            Name = "User32",
                            Password = "$2a$11$94JP16VrKUbw/P4.yLleeupQFnE/5eRANtK34KAJhzd0LN6c/kpD6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("21f9b2cf-b6ef-4d11-a0ba-818d26d7a006"),
                            Email = "user33@example.com",
                            Gender = 1,
                            Name = "User33",
                            Password = "$2a$11$BhSw19mPF9KurX.etIdjc.TZAr9TOhhp6Rx5aAaSaC.VXofiozfxe",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("883f74e0-5e1a-4a79-861a-ecb314a07fba"),
                            Email = "user34@example.com",
                            Gender = 0,
                            Name = "User34",
                            Password = "$2a$11$ui3CKXT6OF0zN6UTli8JbOFrxPbReEbKTGxI99UfriGFr8EikNoPC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2c4dd255-2a45-45f8-ae1f-fc8851d3782a"),
                            Email = "user35@example.com",
                            Gender = 1,
                            Name = "User35",
                            Password = "$2a$11$mavYOZ0bc4TU3OX/PZWfTuOhMTMENPNFAQloTGlD8KhAxRKmEHvDG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9f33c46b-4abd-4fd9-bc83-7b7f9f74c491"),
                            Email = "user36@example.com",
                            Gender = 0,
                            Name = "User36",
                            Password = "$2a$11$9p4GGX15DvDZUzHe8z612eFcxKOXhZf9tSs2N33SDOtDcAu7sFnwi",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7263f1f1-a731-40e0-a94a-e96eab6424a6"),
                            Email = "user37@example.com",
                            Gender = 1,
                            Name = "User37",
                            Password = "$2a$11$rOZ9U8YAEtrA2Fxy3QCbSe9KPTCXy8BLs8NqtS71WuLMaYenhg3XC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8815dd6f-0311-4e85-b233-985960745df6"),
                            Email = "user38@example.com",
                            Gender = 0,
                            Name = "User38",
                            Password = "$2a$11$ImQouVnJIQlu7saiYYlz3eoiiKhi8yD9qKPtoP8AV5o9vQaJvr.ym",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2215e8fb-a6f5-4b37-8b50-7a6b02d581d6"),
                            Email = "user39@example.com",
                            Gender = 1,
                            Name = "User39",
                            Password = "$2a$11$w/Ho44C9sA/bCsacEmOqpuTQiBkeLR/8zGhpOidskM7KpuBYNAvdO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8b6b979d-a208-4c2e-8815-caa546dee237"),
                            Email = "user40@example.com",
                            Gender = 0,
                            Name = "User40",
                            Password = "$2a$11$kZUouO5vY1eTV/InpZv1y.IIACuG9nTZqqum7Xc3jBVkUz9y4FTZa",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("49a9aae9-2b91-4812-a7d2-c96d7a2cb973"),
                            Email = "user41@example.com",
                            Gender = 1,
                            Name = "User41",
                            Password = "$2a$11$wCbgMm2IpanoP3kT9owH/OrhflsGEtADFmjePxoNhMI0VdYDBRg1W",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("fa737043-6a38-4793-a8b8-de4fa410862a"),
                            Email = "user42@example.com",
                            Gender = 0,
                            Name = "User42",
                            Password = "$2a$11$hWYkzXskCyrqRQbIVFi5U.uHuWBt2x7.XS/NjaGUM4mH8LcZwm7yW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("cc196503-7307-4280-a8f7-42bbca4f8c24"),
                            Email = "user43@example.com",
                            Gender = 1,
                            Name = "User43",
                            Password = "$2a$11$/ohM4EEvESWrJp0WHIGkyeJLOS5vQmtVetb/9zPNfai6fXwzDbHPG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b01b7f37-433b-4529-94d0-3644ef9724e9"),
                            Email = "user44@example.com",
                            Gender = 0,
                            Name = "User44",
                            Password = "$2a$11$JmgohDuadLsdISbhc//Sgu4End4mpIEPkHWrySDIq6Y7oHQGIROGK",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6bbdefc6-358d-4a57-9fea-4ac4d31cf0df"),
                            Email = "user45@example.com",
                            Gender = 1,
                            Name = "User45",
                            Password = "$2a$11$u/X4fj3mZF0ieAG125QLs.06p61Y2UUb4q5CI2SVr6HHQZHoijlR2",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8c8d2905-6abf-456e-9044-81c184b4d223"),
                            Email = "user46@example.com",
                            Gender = 0,
                            Name = "User46",
                            Password = "$2a$11$6SrH1UZc/lA3BNi5NjM7DuAx62nZhN61bsh5OwzX1kQnzJbPpeIBS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("740a0023-5020-430b-abf7-39b8b24a398e"),
                            Email = "user47@example.com",
                            Gender = 1,
                            Name = "User47",
                            Password = "$2a$11$npYQwB/9ZwA3mEInFdb9OO0FoTbjInIhTeS9hix8vgf2W4HMWzvoS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("86a09aca-ead3-4708-916e-38f6f293236d"),
                            Email = "user48@example.com",
                            Gender = 0,
                            Name = "User48",
                            Password = "$2a$11$TMWkOCEWe5QXinRPLtDMmOyx1duGnff.t9LJd/PKIXjUqkVSQBj.u",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("28223e42-61a3-4d19-a48a-46296a43de79"),
                            Email = "user49@example.com",
                            Gender = 1,
                            Name = "User49",
                            Password = "$2a$11$95dOPgjOOqLek2NDVK.3ceefLIFNKMyhfu6Gbo8z6QxCXII/Q6e6C",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9e5e4896-b923-4cd9-841c-77fa1fe6537a"),
                            Email = "user50@example.com",
                            Gender = 0,
                            Name = "User50",
                            Password = "$2a$11$tdQAOI5SqIcefjlTNwawnuvgMVd2KKcDa0ttDXgNPd0sGE9AXa3.C",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1f50e98b-1acd-432c-8d6c-49e5f94ec654"),
                            Email = "user51@example.com",
                            Gender = 1,
                            Name = "User51",
                            Password = "$2a$11$TmKHi6zc.HoyXs6p0TcRFuQYqyEQvhzx2LKu0xoNT52KT4ggCN4me",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("78e58e86-5e6c-4c00-add1-739b665768cc"),
                            Email = "user52@example.com",
                            Gender = 0,
                            Name = "User52",
                            Password = "$2a$11$pe8/nM1f2YeIHttNzRgjcubxAO8kQttRvQvS3YusfqPj57XiRW/tC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("84c17fb7-3997-4eb9-bcbe-02a606f6ea56"),
                            Email = "user53@example.com",
                            Gender = 1,
                            Name = "User53",
                            Password = "$2a$11$VGK0o4aJ4R.s7fmilqKSQexnty7/3xyfvUhBryL2I.71B7fdWVNGm",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("93d265cd-a39f-4cce-b97f-ed5b031eee35"),
                            Email = "user54@example.com",
                            Gender = 0,
                            Name = "User54",
                            Password = "$2a$11$xnSUN1iv..rpxp25.GVRre.Rb5XcDt0E9VQ6mTDiq/0Bb1E8fjFse",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2e89e813-5a6a-41c3-8893-190a31ef8bd5"),
                            Email = "user55@example.com",
                            Gender = 1,
                            Name = "User55",
                            Password = "$2a$11$mcDCKzJZa2Xbhi0hthnPSeImX1bqyfQweLpmWqfEIoHkpcsvGMERC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2d3ec0d3-130b-4bd7-8202-f57387412d69"),
                            Email = "user56@example.com",
                            Gender = 0,
                            Name = "User56",
                            Password = "$2a$11$a11Ceo73UjI0V4Nensy2ROorJljVMnQ.2.92u9gbRNwQdXQm36.oO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("145b1d2f-1da3-4bec-a978-539a332c1649"),
                            Email = "user57@example.com",
                            Gender = 1,
                            Name = "User57",
                            Password = "$2a$11$CfxXkWoU.jGEuJINiY/1ze57EY1kBRlIjhk.e7Gi2p1.iHi/xPWVS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1e67b20a-c523-4178-bdf5-16d452781b27"),
                            Email = "user58@example.com",
                            Gender = 0,
                            Name = "User58",
                            Password = "$2a$11$JobeA36CKGL/TUk4DGQmd.OOuPetG3RgPaZnRSmBrk4rCRpvLQOkW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2471054b-a45e-44fd-86d9-2af2f6345793"),
                            Email = "user59@example.com",
                            Gender = 1,
                            Name = "User59",
                            Password = "$2a$11$eBqhDvbOscBvSmZC2jiUj.mHc8nELteGhNo5fchdp3B3awlGZ4Dxu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0c77ee4c-b8d6-454e-978e-be2257dd2e3c"),
                            Email = "user60@example.com",
                            Gender = 0,
                            Name = "User60",
                            Password = "$2a$11$rzsazdFKBIsrSTeTZNcfR.g1IuMO8zNmXO9y2DCpiF.HryWsc66zW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3dfce0b1-7d61-47ff-9053-1b18a3a9a69a"),
                            Email = "user61@example.com",
                            Gender = 1,
                            Name = "User61",
                            Password = "$2a$11$E8tpArTCNbajz/6JFBdnae9k9Cs3LrZXYRk9ycPTXuaDBqY0jDpnG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0f2c23ef-8e11-4f85-85ba-78ccd150d9bb"),
                            Email = "user62@example.com",
                            Gender = 0,
                            Name = "User62",
                            Password = "$2a$11$hMI1tkyLgyMxGKiMmVOro.jGLn1ZNoRmopZnCqEO979DhOZm6XU3m",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4506f837-d214-48bb-8a71-5faea5494c83"),
                            Email = "user63@example.com",
                            Gender = 1,
                            Name = "User63",
                            Password = "$2a$11$4Q0irolbqBO5qiABwQh8qOR9j8QUGxPITS/RJPVrRHjXCTelvTRd6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a5966ef9-31ea-4e17-b5f3-bfcc2920297d"),
                            Email = "user64@example.com",
                            Gender = 0,
                            Name = "User64",
                            Password = "$2a$11$mB0gfcFZawwU1BZuFqmLQ.vWeACTs15DSn.7N7FOE2IB2vVienPJ2",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5312113a-ce17-476f-bf87-5e3a861027c2"),
                            Email = "user65@example.com",
                            Gender = 1,
                            Name = "User65",
                            Password = "$2a$11$vICdYXZh4WJ.ncHXK8E3Oeckh1Ik2UoP4IyA4XKZuo0JaO5B7Szdu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7897a73e-7546-498d-bde6-4f0a8abdd24d"),
                            Email = "user66@example.com",
                            Gender = 0,
                            Name = "User66",
                            Password = "$2a$11$W1hrW3dKYFeNQa6F13.rJuCU5lzkDFTk356D4qe4ClpYZ7pJNOnge",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e4100d6d-dd3a-4a08-9206-fba2e9e9e536"),
                            Email = "user67@example.com",
                            Gender = 1,
                            Name = "User67",
                            Password = "$2a$11$wo1FVhjefK2dGRXhd/QvS.NDiBnj4F6e30HA/8OWfnvCXN4OPLUcm",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("bc16147c-3863-483f-ab18-cfbdb91166d8"),
                            Email = "user68@example.com",
                            Gender = 0,
                            Name = "User68",
                            Password = "$2a$11$ryWx9oRJ18x5GDzTpDcyN.i08.dlht7g.vpMETzef9cmWuI/jcsw6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a521b155-dc28-4c92-bf3d-1ce2b745f892"),
                            Email = "user69@example.com",
                            Gender = 1,
                            Name = "User69",
                            Password = "$2a$11$l5rn/fhHZFvnEI5gJyIh3Ob7rdIJgwUm/RJSQvd4FZKCsvQXVBdTG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3e546a14-ccb5-4e75-92f5-c1f3614953a5"),
                            Email = "user70@example.com",
                            Gender = 0,
                            Name = "User70",
                            Password = "$2a$11$PCri6GqAC6xTglnlbipUBez1Z3RL7pvFMAOc0rvryjYmb2bhyB5Fa",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("ce52fca6-72d1-4d97-a529-401a09648b9d"),
                            Email = "user71@example.com",
                            Gender = 1,
                            Name = "User71",
                            Password = "$2a$11$ceAxm3mZZOwGQQOdk05jKOsy60GjiA9VPRhL5t/VboF1h1YYiso5C",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8a6ee593-0716-4ecb-96a5-ecfe1ea596c9"),
                            Email = "user72@example.com",
                            Gender = 0,
                            Name = "User72",
                            Password = "$2a$11$rif3F0uXzkF3i8yKT838P.eVUz.Q8LQG2OJ5FGCD.Tm8G8Zq7OQOa",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b30cbdab-d85f-441f-8859-e9588cd6527f"),
                            Email = "user73@example.com",
                            Gender = 1,
                            Name = "User73",
                            Password = "$2a$11$UfE2i47KsuRnXvuuJvj7m.ln8Fg6hLx4LeTm6SngEvgejf.AI8vSW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8554f8f0-8c01-4ea7-9982-d9696e59f5d7"),
                            Email = "user74@example.com",
                            Gender = 0,
                            Name = "User74",
                            Password = "$2a$11$mYU/M.Mj4i05Xs5/HVyByuLoi5N1oviXU5EutuBhMTN.J5GAR8AEe",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0abe5794-e3d6-4950-a75e-3d83ed9f022b"),
                            Email = "user75@example.com",
                            Gender = 1,
                            Name = "User75",
                            Password = "$2a$11$eSY9E9KX6m.laUW9UglyHOfcKNUvuO5eVirpZxUVACOFe48YZQmQG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b54be218-f3ed-44f0-a88c-8e3362a2f9a1"),
                            Email = "user76@example.com",
                            Gender = 0,
                            Name = "User76",
                            Password = "$2a$11$vRDvVTq1xaSz/aKKWmsDq.FaPt2dceFFgFxTLvnXjAVVL8qQR6Nyy",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("30e1d0f3-ccae-4785-ae51-52e6c994aacd"),
                            Email = "user77@example.com",
                            Gender = 1,
                            Name = "User77",
                            Password = "$2a$11$J0/hCe1wpr40thQBicIUjec81Zh8NgW9bnWg8VoJMxh8MccZjZfca",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("da2a8d35-b8b4-4679-b0fb-f33cfe973459"),
                            Email = "user78@example.com",
                            Gender = 0,
                            Name = "User78",
                            Password = "$2a$11$wNxR0KLHDRhIxnNSN4LjyeVi9sL1IHxdRlexbkBb.SErXsGOvxiJS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("eda6168b-6515-4b5f-a4ee-6af2a31312f9"),
                            Email = "user79@example.com",
                            Gender = 1,
                            Name = "User79",
                            Password = "$2a$11$bZMqREhCdjcEpdt8aa9BmupMBUW6N9BZTZln8z1GhAilbp/w/RqBK",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("731fb401-e0cd-4aee-bf79-7a3fc0e5f69d"),
                            Email = "user80@example.com",
                            Gender = 0,
                            Name = "User80",
                            Password = "$2a$11$VLvQWsIyYoAjUZmRFYr2DusVms.R1a2S8OCErTyMslpo.xWEfp5v.",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("f97b231c-31da-49a3-90eb-306bef8c72c1"),
                            Email = "user81@example.com",
                            Gender = 1,
                            Name = "User81",
                            Password = "$2a$11$gslnJKCVLQPh0D876E1ZouMmi39H4ul115Qy.yVCn.Vyy8zhSHfj6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("10148a74-60c6-4888-9f69-70a74945d394"),
                            Email = "user82@example.com",
                            Gender = 0,
                            Name = "User82",
                            Password = "$2a$11$zjXQ4nXdokomUgYrP6.jsuD1IBcq/YKfi7UBakHERWC9IJJn6.nIO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4e37bbbb-642e-43f2-83bf-2e70402016a1"),
                            Email = "user83@example.com",
                            Gender = 1,
                            Name = "User83",
                            Password = "$2a$11$wGuLASFkEnv7w7IpCuwHheX2Bf8MdMgaJ7i1WlJFDXx73raTq7ax6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4efa3c17-9aed-4182-9bf6-1e9dce436d13"),
                            Email = "user84@example.com",
                            Gender = 0,
                            Name = "User84",
                            Password = "$2a$11$/Mz3tnIzOh2adJdSceTIPu1TyG.F729JhjTV2Bk2U0sCYUs4BoJRm",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("30912a18-6188-4bd7-b266-1bc5a56e0e06"),
                            Email = "user85@example.com",
                            Gender = 1,
                            Name = "User85",
                            Password = "$2a$11$SdoZ2VYT6rBJn1B4PT/zV.HodVz2pfWc2/K/pt4dy/L.Q7FGMdQUC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4c682287-c7d1-49bf-8baf-012590d02fff"),
                            Email = "user86@example.com",
                            Gender = 0,
                            Name = "User86",
                            Password = "$2a$11$uUnruLYJm.Cp3weSH7PKCuUrhSYV6H0MqWyH2tlkFO58Cf0yCNAse",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6f77416f-8c2e-455b-82dc-346345f1cc66"),
                            Email = "user87@example.com",
                            Gender = 1,
                            Name = "User87",
                            Password = "$2a$11$SNml2GD2lrAqudnlvzZ9penSwNMP5vLUbrjBoVMJZFLNNsVmczj4u",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2292e013-8588-4fac-9676-8582b686d631"),
                            Email = "user88@example.com",
                            Gender = 0,
                            Name = "User88",
                            Password = "$2a$11$q5rOcKveMQOlN7ZIheGnpO9NmTe9XQmU16rLX10I9sdCXU8tSwjUS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("f75fccc3-92e9-4827-ae42-b6500c968337"),
                            Email = "user89@example.com",
                            Gender = 1,
                            Name = "User89",
                            Password = "$2a$11$5.WnMtrBwmmt/BvKePg56e.JPXhLzRL7UOkzRVqc0hpXizTtWTMMi",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("57ef23b1-38f3-41fb-9bf0-c5470eb193a1"),
                            Email = "user90@example.com",
                            Gender = 0,
                            Name = "User90",
                            Password = "$2a$11$TRG5poPl2L4HDaX3.PaZM.nlhw1nlt39v1IIV552l4dbFO02CUeae",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a13bbaf6-66a3-4087-b7f4-9b5c7e472bb2"),
                            Email = "user91@example.com",
                            Gender = 1,
                            Name = "User91",
                            Password = "$2a$11$HRZEqbcMVwUpI41XuNMRmOCU/atDcd.45ayv.31FHKlM2Mpx7kXSG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("50d128ec-ca48-44f3-9248-0d00c4a8cb6c"),
                            Email = "user92@example.com",
                            Gender = 0,
                            Name = "User92",
                            Password = "$2a$11$DZuP8h579dQhcWkDj5e8SufQHvpuFCdiLFURdL48DI34ozcf3dBeG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("f5a82c47-1dc2-41cd-9546-8c62b5b08045"),
                            Email = "user93@example.com",
                            Gender = 1,
                            Name = "User93",
                            Password = "$2a$11$4Miv8PD71m6qJcnKB4cYc.xn.M1YH8wdR6nV2d8qY.KEXMEAjExd2",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e038d487-a20e-4b00-8777-3730b05a7c67"),
                            Email = "user94@example.com",
                            Gender = 0,
                            Name = "User94",
                            Password = "$2a$11$IDcZRTYXJFDAwkxWTm5HmehVAHnrvwboWhy7BkdbMp6ByX95609kW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a329d081-971e-43aa-a388-9683e85697e6"),
                            Email = "user95@example.com",
                            Gender = 1,
                            Name = "User95",
                            Password = "$2a$11$UZLqRd.ooY1JCY2PgA7CPOWufx8Z5vC/8dmBeK.ma.lFmtx4nrfX6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("992f6210-4e0d-4578-b3c5-e09a02bbdaca"),
                            Email = "user96@example.com",
                            Gender = 0,
                            Name = "User96",
                            Password = "$2a$11$b.o.0rTon83i4/bvx11U9uIwM/qpYHCsKqrZQ0b58.p1u3wp6eWsC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a957989e-226f-4bb8-afa2-94e6d40998e9"),
                            Email = "user97@example.com",
                            Gender = 1,
                            Name = "User97",
                            Password = "$2a$11$Sg9ZLabBcd.o.u6CA8PO6utOLC.CO4UiJZ4emIVOP/cr31BGg7gT6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0fb0c78d-3129-4405-b10f-739deea74b39"),
                            Email = "user98@example.com",
                            Gender = 0,
                            Name = "User98",
                            Password = "$2a$11$AzSLs7U/fN/FnQfr8N8Y1usenh9BDMsIa0oFSsKU0ZB5zQLLqrVH2",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a41982b7-d58c-42ff-942b-31059e50140a"),
                            Email = "user99@example.com",
                            Gender = 1,
                            Name = "User99",
                            Password = "$2a$11$7yiRqkRxSghTrteZ71Qe0eStSv8kFIhFxCIYuNA3IX7IQwsx3PKdm",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7e80f554-4aa0-48f7-84ed-64f60ebd8099"),
                            Email = "user100@example.com",
                            Gender = 0,
                            Name = "User100",
                            Password = "$2a$11$EpnjjI0N5k3puA6hn3Dk9epFPvOD5DPCGmb5jJke/PjXj6VFDR9Ge",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.HasOne("PassSystemTD.Entities.User", "User")
                        .WithMany("Passes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Proof", b =>
                {
                    b.HasOne("PassSystemTD.Entities.Pass", "Pass")
                        .WithMany("Proofs")
                        .HasForeignKey("PassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Role", b =>
                {
                    b.HasOne("PassSystemTD.Entities.User", "User")
                        .WithOne("Role")
                        .HasForeignKey("PassSystemTD.Entities.Role", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("PassSystemTD.Entities.User", b =>
                {
                    b.Navigation("Passes");

                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
