// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PassSystemTD.Data;

#nullable disable

namespace PassSystemTD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250307140502_FixedRole")]
    partial class FixedRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PassStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Proof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PassId");

                    b.ToTable("Proofs");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDean")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dbf9137e-6db4-4bd6-af02-e9a6d7048d6a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("338e0d84-f583-4e72-9681-db592231ec39"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("054d595a-593b-4a37-b074-7bb8dbef619b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("ccc312a7-d1c4-4d24-a54b-b68b24766b0f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c20d369d-e81b-49b7-af33-926efcc5f349"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("91c72994-e23e-42d7-9853-1276c2ad5967"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("e045f227-b146-4c2a-a94f-26c712c7f7ef"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c1c950ab-0ce7-46df-92c6-41aee1d9f313"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("e6679657-10f6-4564-a1aa-0c755264aef7"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c968874d-168e-44da-9e7b-ccd45d8d7f05"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("b4bdc4d5-6bb5-4967-a929-982b1f35017f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("2424580a-04f7-40d5-b12f-4dd7b6e88e95"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("02dfa0f5-a524-404d-be67-6806eddf1ac9"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("02fa75f3-538c-4ac7-a783-793617acb817"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("f8fb2f43-3db5-4d24-8d91-aec910d19da5"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("390c981b-0a74-4bd4-a4b5-4e5b44cbde2e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b09027c5-8bee-4d4c-ba58-f5ac8a06eb3d"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("9e53c14f-e443-4a2a-993f-2c74ac0d1787"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("600f6c61-3a7c-4806-ac76-a3dba81b4042"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("355633b6-8523-4f06-b256-130894ee0c65"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("ef59e76b-2b3f-4b30-9458-c891e3c85cd5"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("268707b3-4f7c-4861-8d96-6639a50b369d"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("fdff63bf-5196-4122-a759-a9d967ed8674"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("42232f21-4eb2-4748-92a6-96bb3fa816db"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("22cc553a-9dd9-4c6c-a5fe-996a13ce1e20"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("86c08a8c-2f94-4f3d-a666-2d4107af3aa2"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("cb7073ba-8d14-4d51-946b-8429d6b1e8f8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("24aa9ade-ac24-44e0-97e3-ec50df7c3a7d"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("5bda4ff9-b04e-4a8a-bf73-0a16c52dfa77"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("f7756e59-a187-4578-b18b-281f02a2d399"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("4ab9f12d-78a4-4805-b23c-c0093717a7b0"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("25641c23-5c3b-4652-b189-18b158414d33"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("3277a1f4-5663-4fdf-8a76-359622a37e55"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("da942392-6f52-4062-8873-650cfb1ad111"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("554ae3de-6629-4ef5-bf1b-b5da1e326a1a"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("8fb0564b-92c2-47a2-a311-a90e91e96983"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("dc9bceba-e1dd-434f-b358-af47a26e73be"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("7c57490e-6352-451e-a44d-a7dd75367ff6"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("8dfc3516-79d4-4960-bc57-ff7431b5bb8f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("4b29a881-301b-4162-9dbe-9a87448484f5"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("c5c24958-cb8e-49ac-9eab-d06d0e26535c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6e645df8-7d67-4968-aba1-59748723c2f6"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("31c8c5a0-22c6-4454-a923-f8084662b039"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("25021999-8ede-460a-8e9d-3cd62378f78f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d676416d-6001-4f2a-baf9-67f15095c951"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("2c991324-71d9-4558-b3f9-09968456b00b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1e4826ae-0f6c-42c8-83ac-0df7af0700c0"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("fc00841d-1b5e-449d-a098-4d79fabe3a98"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("a541de40-12ec-4dd1-bce7-65b640ea6e49"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("352b2986-71ed-44d5-979d-87de83aabcc2"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("b7366270-77e0-4b14-bd44-11215cdd568f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("cbdac6c7-9268-4cf9-9528-a9ac3e31ba6e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1cc6be3a-9978-4152-9718-366ba8471445"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("31a91bbf-ca65-459e-a20f-b7f6dbd67b83"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d6b610bc-1713-4281-aa07-eab7df370037"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("d844ad1a-67a6-4a5b-bdf2-30887afbf7c1"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c2a56740-50b9-4933-b93c-f05c5fed3839"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("451fbeca-e948-47e3-8eb5-cc051f9d1e2a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6847d61d-71a3-48c0-8ce3-1bfa9f2e329a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("62b928ed-4d68-447f-ab20-515114ab7583"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("f2534357-b043-4b85-8c86-10a49de4a701"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("51e7aeb1-4d81-46b0-afbc-40edceaa6975"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6e9c01f8-565f-480b-a40d-0fe618fd5e1c"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("80f4f8e1-165f-4daa-b423-9c61ef4906e4"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("da1179d6-6753-4df0-83a1-6b8b5adbb713"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("7cd57e07-b554-4ee4-8402-8ef277f91f4c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("661820ee-d643-4586-be72-53422b52e6c9"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("18303189-52c6-4e73-b206-0f2211be3492"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("5bec4830-e709-4f11-be43-fc3de4f86d5f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("3015ea6d-aa37-414c-a5d5-2f90a509b717"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("04afe721-cc98-4a17-9b71-03ce98215e2f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("5e107b93-1d6e-4888-ad44-eae6570bd9b6"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("a3a49cff-1fe1-4e5d-b4ad-2f044e5c496c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1165e693-0e40-48f1-bb2b-c1f2e2837ff1"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("95ead1e6-dd25-4211-9379-c0913c54ef96"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("f3270699-8563-400e-87c1-bcf7b87a1ad3"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("743c7a56-cf2b-4364-921a-c0e5f3ea4f69"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("5fabac1f-22ed-4b6d-86f0-ef2cd1925f71"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("404184e4-5feb-4f80-b989-5ca81b2a9661"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("94f48908-632d-42ac-bbfc-31aa1a4cc6b9"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("d7524c60-8aeb-468c-8102-07da9808a9f9"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("5aacb7e1-62f1-41b9-a799-1948f48cbdde"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("131196fc-78bc-4d00-8e24-a52510697e1b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b8095c10-7f45-4d4e-b8e4-b312c9388100"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("f4ac4af5-057b-438a-a8e4-7e67bc656837"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("4ee18cea-acc7-4022-9be0-d2165584b1df"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("5990c572-1953-4756-b082-02a602e92cb7"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b09296ea-f679-49b7-bb3e-fd0dafee398b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1952d507-7574-4ea8-af35-dda2d392078c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("cef0842d-9599-4b17-9e02-ea090254bd1e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("4bef3b42-1470-4b05-9271-9ad09364ac6f"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("3e985afc-1963-4f46-9de6-fda64bbe6d2c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("bb2a45f9-a07f-4739-9b20-4bbd46bae07b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c7f5132d-d706-423b-a3af-f90611469788"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("64be8ba5-604f-42ad-a339-0f1ee7142c93"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("3ce04e3a-186a-4bd6-8ffe-47f210341b25"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("dc3d38c0-a982-4635-94a5-61807d522432"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6f384cfd-1a56-48a8-bb98-65fa0dbca5d6"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c0bee675-885f-4ff8-9fe6-be7d18aa2538"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c01ede05-beff-4344-b664-f22eba96a23e"),
                            IsAdmin = true,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        });
                });

            modelBuilder.Entity("PassSystemTD.Entities.TokenEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Token");

                    b.ToTable("BannedTokens");
                });

            modelBuilder.Entity("PassSystemTD.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dbf9137e-6db4-4bd6-af02-e9a6d7048d6a"),
                            Email = "user1@example.com",
                            Gender = 1,
                            Name = "User1",
                            Password = "$2a$11$OiTO75Q0qIFvDNqZPuwS2uePPLNEiybss23xchNJvSkCyyFjuxVJu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("338e0d84-f583-4e72-9681-db592231ec39"),
                            Email = "user2@example.com",
                            Gender = 0,
                            Name = "User2",
                            Password = "$2a$11$TkqL5/djl4pPbj6CY0GZjeUfuaORHi1n.xCypv.YqIDs6rXT6tvcS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("054d595a-593b-4a37-b074-7bb8dbef619b"),
                            Email = "user3@example.com",
                            Gender = 1,
                            Name = "User3",
                            Password = "$2a$11$78sl71g8aTlDCgOQWHX/BOo8PGepNlUJ.taXHFhVOYage6TbLNRYW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("ccc312a7-d1c4-4d24-a54b-b68b24766b0f"),
                            Email = "user4@example.com",
                            Gender = 0,
                            Name = "User4",
                            Password = "$2a$11$DkEV5P6VTpmoeRvJjo149eDjsCCSODiMIR20ZGXHLHy81jORFS19e",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c20d369d-e81b-49b7-af33-926efcc5f349"),
                            Email = "user5@example.com",
                            Gender = 1,
                            Name = "User5",
                            Password = "$2a$11$uTZwCb1nbxAliwoPFyu9/uPy49CmaILRMWUIr8TmUGKi22BGGpYoq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("91c72994-e23e-42d7-9853-1276c2ad5967"),
                            Email = "user6@example.com",
                            Gender = 0,
                            Name = "User6",
                            Password = "$2a$11$zf1Xh2fMfQhDWuGMCp5VTeVZkt9cCSHkWUWxpDmv9tHqqIENnCSwy",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e045f227-b146-4c2a-a94f-26c712c7f7ef"),
                            Email = "user7@example.com",
                            Gender = 1,
                            Name = "User7",
                            Password = "$2a$11$NT0OnN6f6wGOBgW6w03STO.vsssnY2oR4hK5cqpKsv.TTIKVeptNq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c1c950ab-0ce7-46df-92c6-41aee1d9f313"),
                            Email = "user8@example.com",
                            Gender = 0,
                            Name = "User8",
                            Password = "$2a$11$niT9j6I4sIFuVHHT4yFmIuqapMAaNL4lqlVkovN8LKi4huK.PM9mu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e6679657-10f6-4564-a1aa-0c755264aef7"),
                            Email = "user9@example.com",
                            Gender = 1,
                            Name = "User9",
                            Password = "$2a$11$iAYdUWk3pgcnPJjPdPlq6.bGcOnoT7wyvlkGTdy7G0ydo.7MUZ2Mq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c968874d-168e-44da-9e7b-ccd45d8d7f05"),
                            Email = "user10@example.com",
                            Gender = 0,
                            Name = "User10",
                            Password = "$2a$11$B3WbvDk6B.g1GFIeBF3jPOFbTOYuOWmGt/s8SlqIdOwmMPERpULZ2",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b4bdc4d5-6bb5-4967-a929-982b1f35017f"),
                            Email = "user11@example.com",
                            Gender = 1,
                            Name = "User11",
                            Password = "$2a$11$BGYdr0zBIEoJXv/LvDZ/se/xMpnrs3Kb5ERqs.9yWME3Pu1whi91m",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2424580a-04f7-40d5-b12f-4dd7b6e88e95"),
                            Email = "user12@example.com",
                            Gender = 0,
                            Name = "User12",
                            Password = "$2a$11$b70jptLamWT48/1cZcg7ruQ7zecxcuVKB.dUmVuPPngLq2Rjzqxjq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("02dfa0f5-a524-404d-be67-6806eddf1ac9"),
                            Email = "user13@example.com",
                            Gender = 1,
                            Name = "User13",
                            Password = "$2a$11$wuEydp8VVynrgYegmpJTh.XHXOWnHSeqUsGLY8zBaUkOzenmloEZ6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("02fa75f3-538c-4ac7-a783-793617acb817"),
                            Email = "user14@example.com",
                            Gender = 0,
                            Name = "User14",
                            Password = "$2a$11$4YVkVIP4sw26RXY1jwAj4OTfw/JhDEyeiiq71ftCDhYYUwUiFzV8K",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("f8fb2f43-3db5-4d24-8d91-aec910d19da5"),
                            Email = "user15@example.com",
                            Gender = 1,
                            Name = "User15",
                            Password = "$2a$11$/kNHC7pp/dX5qS0BESTbn.NEUvsbuwrYuXYguH0oLfxDWd0Awbeau",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("390c981b-0a74-4bd4-a4b5-4e5b44cbde2e"),
                            Email = "user16@example.com",
                            Gender = 0,
                            Name = "User16",
                            Password = "$2a$11$vHNO0J8d7XrZdu.e7bMeTO2I24akSwAmFP/ZlBZpFxlxeaczlQ50.",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b09027c5-8bee-4d4c-ba58-f5ac8a06eb3d"),
                            Email = "user17@example.com",
                            Gender = 1,
                            Name = "User17",
                            Password = "$2a$11$2P.EOCXjUgwrNaUGAo7Kn.9LXPfjfuOgETrFsX0cm1XSbEcQCP/cK",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9e53c14f-e443-4a2a-993f-2c74ac0d1787"),
                            Email = "user18@example.com",
                            Gender = 0,
                            Name = "User18",
                            Password = "$2a$11$YXS8BG.gXDda.2cvDbD2SegvdFDNzdfBnhwt9yyOtwpMU4/65E4aK",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("600f6c61-3a7c-4806-ac76-a3dba81b4042"),
                            Email = "user19@example.com",
                            Gender = 1,
                            Name = "User19",
                            Password = "$2a$11$Gj4qU/iSdI7KMtkTyWsgHOqAMqHwweBgcjdgAoN1HVfuYJ1ssafAO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("355633b6-8523-4f06-b256-130894ee0c65"),
                            Email = "user20@example.com",
                            Gender = 0,
                            Name = "User20",
                            Password = "$2a$11$bzeNAGr.MZWo8YLcMKgCReAp5Z/.OCy0z3NU2Tk5imSwFxSR8nixm",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("ef59e76b-2b3f-4b30-9458-c891e3c85cd5"),
                            Email = "user21@example.com",
                            Gender = 1,
                            Name = "User21",
                            Password = "$2a$11$ljhSwsOvolot7AqOwKRgPubP.FJoVyaGkyEKCAUNBM7Np.rMH9LuS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("268707b3-4f7c-4861-8d96-6639a50b369d"),
                            Email = "user22@example.com",
                            Gender = 0,
                            Name = "User22",
                            Password = "$2a$11$F4gt.qr7/vlLcrfTdOwipOVPoKr62P3el.7UclBuG3MXoDkyG.XqC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("fdff63bf-5196-4122-a759-a9d967ed8674"),
                            Email = "user23@example.com",
                            Gender = 1,
                            Name = "User23",
                            Password = "$2a$11$owDrYJkTCLKCCX9QnJGFoePTvh7SCb06bY.FBBYCFQWyDt4BmSIu6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("42232f21-4eb2-4748-92a6-96bb3fa816db"),
                            Email = "user24@example.com",
                            Gender = 0,
                            Name = "User24",
                            Password = "$2a$11$1uFd6wDccmNUhkcRb4E7kuyV2MYsvt3O31SDtACx3DclK.f1zygV.",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("22cc553a-9dd9-4c6c-a5fe-996a13ce1e20"),
                            Email = "user25@example.com",
                            Gender = 1,
                            Name = "User25",
                            Password = "$2a$11$jRRhLZ8CnL5J2NYE1szoTOD7rQobJRaRmqvyWfd8UWErNaXXFespS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("86c08a8c-2f94-4f3d-a666-2d4107af3aa2"),
                            Email = "user26@example.com",
                            Gender = 0,
                            Name = "User26",
                            Password = "$2a$11$E8UA.ekQwrLbXz/C4RlT/.AmPHki4K6Gy3YihDq8UtJ4U5Lwp4pFu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("cb7073ba-8d14-4d51-946b-8429d6b1e8f8"),
                            Email = "user27@example.com",
                            Gender = 1,
                            Name = "User27",
                            Password = "$2a$11$ZN7O1S2dkY0SippqWkh/aOHdxt18/sYneSYXGRfVJp2QxGTUqLW9K",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("24aa9ade-ac24-44e0-97e3-ec50df7c3a7d"),
                            Email = "user28@example.com",
                            Gender = 0,
                            Name = "User28",
                            Password = "$2a$11$va5u9RfTilFcbiVrUVpR1eBjlS.1cnlExzQekniEoUF40q1DRyOGK",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5bda4ff9-b04e-4a8a-bf73-0a16c52dfa77"),
                            Email = "user29@example.com",
                            Gender = 1,
                            Name = "User29",
                            Password = "$2a$11$zK1ZwmVan5LKVL2Yliisi.RhvKMJku62H6v2yN/WRaXLKZm54kvg6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("f7756e59-a187-4578-b18b-281f02a2d399"),
                            Email = "user30@example.com",
                            Gender = 0,
                            Name = "User30",
                            Password = "$2a$11$5vrPOVhdFAQbDK2oNHTVSOHm8S2Xg/jQU51KF691bcGMYTiSt1hWO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4ab9f12d-78a4-4805-b23c-c0093717a7b0"),
                            Email = "user31@example.com",
                            Gender = 1,
                            Name = "User31",
                            Password = "$2a$11$n2qVlyy0xPoHSOqzro/5zumcuprbhAnaeudWbNzgQvJ2/CcYzlFWC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("25641c23-5c3b-4652-b189-18b158414d33"),
                            Email = "user32@example.com",
                            Gender = 0,
                            Name = "User32",
                            Password = "$2a$11$he5LgIxNsLj48b7ly8Jh0uIBhUoLtZ27mnNN5kiwHrCYvH4T4Lm8q",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3277a1f4-5663-4fdf-8a76-359622a37e55"),
                            Email = "user33@example.com",
                            Gender = 1,
                            Name = "User33",
                            Password = "$2a$11$o6kYqgLpMjU3h6uXN1i.kevReHLT/rsLu16tZmhAnmahiUuldOz4.",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("da942392-6f52-4062-8873-650cfb1ad111"),
                            Email = "user34@example.com",
                            Gender = 0,
                            Name = "User34",
                            Password = "$2a$11$MF4aU/bkwKRFpDh0BvjytukK54X2FqINltZqxHp.MumHPosQfF5em",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("554ae3de-6629-4ef5-bf1b-b5da1e326a1a"),
                            Email = "user35@example.com",
                            Gender = 1,
                            Name = "User35",
                            Password = "$2a$11$80sKc0gU6VXvJp.uVe1jfOWDQ40JtrhGOUfQL2/.veMx2Jnqgh5F6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8fb0564b-92c2-47a2-a311-a90e91e96983"),
                            Email = "user36@example.com",
                            Gender = 0,
                            Name = "User36",
                            Password = "$2a$11$d2hM77SGYCfw0i2XB1r3l.UNO3MpASuotrIvrxQoPawDeJUmmFGgu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("dc9bceba-e1dd-434f-b358-af47a26e73be"),
                            Email = "user37@example.com",
                            Gender = 1,
                            Name = "User37",
                            Password = "$2a$11$.Dt2xg8enaKz9X4LujaWBulRJ3XTZxwsDeaqTNhhKLiB3BA3Iruma",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7c57490e-6352-451e-a44d-a7dd75367ff6"),
                            Email = "user38@example.com",
                            Gender = 0,
                            Name = "User38",
                            Password = "$2a$11$HUFz7pDKsEvHBxpyNtVKKe2XDa5Ng9U6t3JFU4UG2ljZrvGZoxUYW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8dfc3516-79d4-4960-bc57-ff7431b5bb8f"),
                            Email = "user39@example.com",
                            Gender = 1,
                            Name = "User39",
                            Password = "$2a$11$sxMn5i0VjYX5Z/i//kZ4vunLKFPJcrAfMCvpVcYokbIWJIn9oEkVO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4b29a881-301b-4162-9dbe-9a87448484f5"),
                            Email = "user40@example.com",
                            Gender = 0,
                            Name = "User40",
                            Password = "$2a$11$4.OfaKzWz5nYxp.eSHYy3OvbtXBOf8FFmyopSM.Ak/rDuQ1nrQkCq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c5c24958-cb8e-49ac-9eab-d06d0e26535c"),
                            Email = "user41@example.com",
                            Gender = 1,
                            Name = "User41",
                            Password = "$2a$11$.V67N8prF9wogyCJIRZbZ.Jec.bbfZQhOLFF/32RVqasFylJv02GG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6e645df8-7d67-4968-aba1-59748723c2f6"),
                            Email = "user42@example.com",
                            Gender = 0,
                            Name = "User42",
                            Password = "$2a$11$GKdTM/GGc4s/Y3eH9.D7F.FvHwlcIrboxf2f4Z/4cOVyexCFARGjW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("31c8c5a0-22c6-4454-a923-f8084662b039"),
                            Email = "user43@example.com",
                            Gender = 1,
                            Name = "User43",
                            Password = "$2a$11$Phf/Gi1px8nMrz0hotopN.AtGj2uEqwIi375xSHBVHHAZv0TYWAZ.",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("25021999-8ede-460a-8e9d-3cd62378f78f"),
                            Email = "user44@example.com",
                            Gender = 0,
                            Name = "User44",
                            Password = "$2a$11$W66hRBKu1gJx5QgXYtHI2OcQz8isMEINWE5DKBSAbp44jP/y74S/C",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d676416d-6001-4f2a-baf9-67f15095c951"),
                            Email = "user45@example.com",
                            Gender = 1,
                            Name = "User45",
                            Password = "$2a$11$00QycRFcqjVCJwoPVrc6Cesx3zqV/eVnd0aM9tmnm97S82lQm1HQK",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("2c991324-71d9-4558-b3f9-09968456b00b"),
                            Email = "user46@example.com",
                            Gender = 0,
                            Name = "User46",
                            Password = "$2a$11$k7je6zq3cNHpupCmM70NjOcBDoP4NstdoVIEIYpkylcGGNXdxUZ.O",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1e4826ae-0f6c-42c8-83ac-0df7af0700c0"),
                            Email = "user47@example.com",
                            Gender = 1,
                            Name = "User47",
                            Password = "$2a$11$JQUQG/7FrDSL5V1LXNwZGe44q1vXkq2JUsqJxBZk4kHx/Uxea2wSG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("fc00841d-1b5e-449d-a098-4d79fabe3a98"),
                            Email = "user48@example.com",
                            Gender = 0,
                            Name = "User48",
                            Password = "$2a$11$YFEwQ/XL1.qAK3EAVn9T2.NZ3Href5eCQkUpNfmukm7r8AFdGF8Jq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a541de40-12ec-4dd1-bce7-65b640ea6e49"),
                            Email = "user49@example.com",
                            Gender = 1,
                            Name = "User49",
                            Password = "$2a$11$KWgRBnT3o9IJSO9xeNNzsO8ND30g8PsPuQiEY4YC9s.Yk3FSfqMD6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("352b2986-71ed-44d5-979d-87de83aabcc2"),
                            Email = "user50@example.com",
                            Gender = 0,
                            Name = "User50",
                            Password = "$2a$11$m9vkq0ENfkDaTp/WdTWTIuobf3yvsYIeDXJN3RuchfGbud.5ATzRK",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b7366270-77e0-4b14-bd44-11215cdd568f"),
                            Email = "user51@example.com",
                            Gender = 1,
                            Name = "User51",
                            Password = "$2a$11$HtNwbJatUVZ1FeGYuaMAuer/4KBV0ICca7rm3b8O2KSCgsIf.Qm5y",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("cbdac6c7-9268-4cf9-9528-a9ac3e31ba6e"),
                            Email = "user52@example.com",
                            Gender = 0,
                            Name = "User52",
                            Password = "$2a$11$eRzxU6CDD37s/ZF4P4cyf..9rdNgIWwbG5GfdMzvkMZ7F4xpP4ftC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1cc6be3a-9978-4152-9718-366ba8471445"),
                            Email = "user53@example.com",
                            Gender = 1,
                            Name = "User53",
                            Password = "$2a$11$6Q9nTL2/sZNuMSd.9MDXMOktizQYqkheaCwuuJcOAqhWRodOLxjfC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("31a91bbf-ca65-459e-a20f-b7f6dbd67b83"),
                            Email = "user54@example.com",
                            Gender = 0,
                            Name = "User54",
                            Password = "$2a$11$GIHb9JUn10VY8DTSlz177uErza76awGEVHOrY32NYXbLPZkA5.0qy",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d6b610bc-1713-4281-aa07-eab7df370037"),
                            Email = "user55@example.com",
                            Gender = 1,
                            Name = "User55",
                            Password = "$2a$11$9zApwwPABnbc/etx8T9OjeslgSQ.18iED1YXEdWsaH9J5SiwbCrIe",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d844ad1a-67a6-4a5b-bdf2-30887afbf7c1"),
                            Email = "user56@example.com",
                            Gender = 0,
                            Name = "User56",
                            Password = "$2a$11$W42oqY2JVjCeO3aDc/fWKeD4sNuWJDUG2xRm4qF6Eg2vIZJeHLWFa",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c2a56740-50b9-4933-b93c-f05c5fed3839"),
                            Email = "user57@example.com",
                            Gender = 1,
                            Name = "User57",
                            Password = "$2a$11$MkCv.nKHGI8pSe0DpJsAGeZiKpBm.ech414h6tbQt3VTVtxGC/4q2",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("451fbeca-e948-47e3-8eb5-cc051f9d1e2a"),
                            Email = "user58@example.com",
                            Gender = 0,
                            Name = "User58",
                            Password = "$2a$11$dacdun9X7GulaVrsX7hl9.mAxd7FLlv1mdXn3yP/p6a5ZIWrKSaHW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6847d61d-71a3-48c0-8ce3-1bfa9f2e329a"),
                            Email = "user59@example.com",
                            Gender = 1,
                            Name = "User59",
                            Password = "$2a$11$eL8YQqJOCzAfTBJKkfy.FeQSRFshAIXTBTNOMjL90JyLI7r5711SG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("62b928ed-4d68-447f-ab20-515114ab7583"),
                            Email = "user60@example.com",
                            Gender = 0,
                            Name = "User60",
                            Password = "$2a$11$5hW9b0QCevLZtY/vgVhfX.gHTzEWj3DX1vF4bVszg62SDPg1Cvueu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("f2534357-b043-4b85-8c86-10a49de4a701"),
                            Email = "user61@example.com",
                            Gender = 1,
                            Name = "User61",
                            Password = "$2a$11$.7xfcTkXTeoo9DnGZ3if3usH4wX88VszVMTDNjca.zz0IJQXb54lu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("51e7aeb1-4d81-46b0-afbc-40edceaa6975"),
                            Email = "user62@example.com",
                            Gender = 0,
                            Name = "User62",
                            Password = "$2a$11$.4WMoZ1DmtYdKw8j6pstIenosRx6ISu7hYvbNhFEicQwcVcRX9MQC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6e9c01f8-565f-480b-a40d-0fe618fd5e1c"),
                            Email = "user63@example.com",
                            Gender = 1,
                            Name = "User63",
                            Password = "$2a$11$TWItErZRiojYopmN8gqcBe0fNn3D9LTK/.d9Towee/GV/1yHGPD6S",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("80f4f8e1-165f-4daa-b423-9c61ef4906e4"),
                            Email = "user64@example.com",
                            Gender = 0,
                            Name = "User64",
                            Password = "$2a$11$zdHl39Rhd6tx/iyCMuU.1eb0/CNhcDJU1hZuc7mlZ.rVNXDuGOf2C",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("da1179d6-6753-4df0-83a1-6b8b5adbb713"),
                            Email = "user65@example.com",
                            Gender = 1,
                            Name = "User65",
                            Password = "$2a$11$KRMVb6oYMsq/m/hWjJ4eMeIAqfG1sNexNJP3PAmxTi1CSNmxgd71W",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7cd57e07-b554-4ee4-8402-8ef277f91f4c"),
                            Email = "user66@example.com",
                            Gender = 0,
                            Name = "User66",
                            Password = "$2a$11$cGsGFum0FcBCTxT0QA31leJOu/4s7XMaqrV12UltW5hN303AKa1SO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("661820ee-d643-4586-be72-53422b52e6c9"),
                            Email = "user67@example.com",
                            Gender = 1,
                            Name = "User67",
                            Password = "$2a$11$3ZrWX7yeMGfSXwyZrpAINu0mV3t6lNTdDJ3CsyA0jSepj3rDMyOYu",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("18303189-52c6-4e73-b206-0f2211be3492"),
                            Email = "user68@example.com",
                            Gender = 0,
                            Name = "User68",
                            Password = "$2a$11$UCz5xGqu.lmjMIJORYAL3eXbuSIfc4l5fAaVhKXh8CBbCS6oGe7/e",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5bec4830-e709-4f11-be43-fc3de4f86d5f"),
                            Email = "user69@example.com",
                            Gender = 1,
                            Name = "User69",
                            Password = "$2a$11$KIXzAZdDIvtxJNv0GJ6kPO0.C/elZcAzedaQGr8XhklFfEmmqaXR2",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3015ea6d-aa37-414c-a5d5-2f90a509b717"),
                            Email = "user70@example.com",
                            Gender = 0,
                            Name = "User70",
                            Password = "$2a$11$dDLtxrcscCGuttAHO/hcoOFFY0I.KsaNZkkf6rwHzmUyssd4jrq2m",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("04afe721-cc98-4a17-9b71-03ce98215e2f"),
                            Email = "user71@example.com",
                            Gender = 1,
                            Name = "User71",
                            Password = "$2a$11$DxA4YRdirnnBuWwQ6ddcpumDJCxxzYn3VLfWjzqXmUG4jfc5vYh/6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5e107b93-1d6e-4888-ad44-eae6570bd9b6"),
                            Email = "user72@example.com",
                            Gender = 0,
                            Name = "User72",
                            Password = "$2a$11$2PKCYkQFzDI.ynvCokTUSeg4N.dCTA7.foWodjIh2XN4ET4yBDIzG",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a3a49cff-1fe1-4e5d-b4ad-2f044e5c496c"),
                            Email = "user73@example.com",
                            Gender = 1,
                            Name = "User73",
                            Password = "$2a$11$O7TzA1PDR0220/9DAWIDte9Y9k/0a6UyWzZqUDYTKqdBksBAfpqAy",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1165e693-0e40-48f1-bb2b-c1f2e2837ff1"),
                            Email = "user74@example.com",
                            Gender = 0,
                            Name = "User74",
                            Password = "$2a$11$kLPeWs3ANAM7V/xhfFnL4OZkF7HO5t7gnbDDcyH9/3cC9kLiDvZ..",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("95ead1e6-dd25-4211-9379-c0913c54ef96"),
                            Email = "user75@example.com",
                            Gender = 1,
                            Name = "User75",
                            Password = "$2a$11$JW8DKT23MsPR4GSgse8YauZ/vGi0TE7YtI1CP4LASKEqBqNmZSl4y",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("f3270699-8563-400e-87c1-bcf7b87a1ad3"),
                            Email = "user76@example.com",
                            Gender = 0,
                            Name = "User76",
                            Password = "$2a$11$9BwjYo/W58bTf9xSsr/SMOmK.F2GOIPnpnhqH/crUIXqAR6TVRiQm",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("743c7a56-cf2b-4364-921a-c0e5f3ea4f69"),
                            Email = "user77@example.com",
                            Gender = 1,
                            Name = "User77",
                            Password = "$2a$11$UuKyonEfMkx799hwg7Dqwu06eOIevZTPEBfyitbfkIXzG1d7S/RaC",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5fabac1f-22ed-4b6d-86f0-ef2cd1925f71"),
                            Email = "user78@example.com",
                            Gender = 0,
                            Name = "User78",
                            Password = "$2a$11$MC5DkBE7F5L30iL71.0ux.wC6sCejF2obpnF.accGUt7Ch5fn1Hye",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("404184e4-5feb-4f80-b989-5ca81b2a9661"),
                            Email = "user79@example.com",
                            Gender = 1,
                            Name = "User79",
                            Password = "$2a$11$axh6K9oeIwtYnUcqRU6UvOSsmH1mpWE1KZiuYiUR0sKWuZpYqn9wS",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("94f48908-632d-42ac-bbfc-31aa1a4cc6b9"),
                            Email = "user80@example.com",
                            Gender = 0,
                            Name = "User80",
                            Password = "$2a$11$mARTOL.oHriAStgGM.hoq.PnY/ifB8ujY.ifLQnPD1W.Y166.C.9a",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d7524c60-8aeb-468c-8102-07da9808a9f9"),
                            Email = "user81@example.com",
                            Gender = 1,
                            Name = "User81",
                            Password = "$2a$11$Quq4F.oPraa2IR.PD/XEj.rTR6hHBkKI6ewEGhdiiivtpGe2DO06u",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5aacb7e1-62f1-41b9-a799-1948f48cbdde"),
                            Email = "user82@example.com",
                            Gender = 0,
                            Name = "User82",
                            Password = "$2a$11$ESvHXC.0mVamrUYhDhxosu3SA2VCYdsU1H2NOXx/K4N4VRIB8jHju",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("131196fc-78bc-4d00-8e24-a52510697e1b"),
                            Email = "user83@example.com",
                            Gender = 1,
                            Name = "User83",
                            Password = "$2a$11$bhKgOnYSxI0axlJ/mgpzUuM/XBjPb7Vl.nHib1DqgScVjediAalae",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b8095c10-7f45-4d4e-b8e4-b312c9388100"),
                            Email = "user84@example.com",
                            Gender = 0,
                            Name = "User84",
                            Password = "$2a$11$C03KZ/iASG4l2DytWnT.dOkMTCG2vzuJhLwOlUIsRMxwa52oGJLLO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("f4ac4af5-057b-438a-a8e4-7e67bc656837"),
                            Email = "user85@example.com",
                            Gender = 1,
                            Name = "User85",
                            Password = "$2a$11$hdpM8qjJhG.g0YrWRYFiAOZrUQDV803C4x30LMBQgnZJNNd6C1ELW",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4ee18cea-acc7-4022-9be0-d2165584b1df"),
                            Email = "user86@example.com",
                            Gender = 0,
                            Name = "User86",
                            Password = "$2a$11$Vq8M/.YN5zKjyrPTSbc6quoieCUA2s/iXfSuh1sRNISv9dhnTCRZq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5990c572-1953-4756-b082-02a602e92cb7"),
                            Email = "user87@example.com",
                            Gender = 1,
                            Name = "User87",
                            Password = "$2a$11$R16GqJihg2UrOAT2yMlA3Og43ulzAb0gcp7ldwyrfmvvFqCHxzP06",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b09296ea-f679-49b7-bb3e-fd0dafee398b"),
                            Email = "user88@example.com",
                            Gender = 0,
                            Name = "User88",
                            Password = "$2a$11$Z2b4Dr6H2vVfBNzqMUnDKO0q0iu.CIEX/wHiAFiLIn55qXhozk8Ii",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("1952d507-7574-4ea8-af35-dda2d392078c"),
                            Email = "user89@example.com",
                            Gender = 1,
                            Name = "User89",
                            Password = "$2a$11$boID1rUevqiHqkxxwJIuqOdWQnYS5xp/6wnEFCDRVwD.jfx.xys.K",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("cef0842d-9599-4b17-9e02-ea090254bd1e"),
                            Email = "user90@example.com",
                            Gender = 0,
                            Name = "User90",
                            Password = "$2a$11$pa1uywLb8IEEy0w3KWOdGe6LFr/IhobuXdrujoyyfYT/Yw/P133Se",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4bef3b42-1470-4b05-9271-9ad09364ac6f"),
                            Email = "user91@example.com",
                            Gender = 1,
                            Name = "User91",
                            Password = "$2a$11$AigA3r3XIvm2ZCfmqPDPE..jlOR3fZXkTZasUAL39jHLIv0Wykf26",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3e985afc-1963-4f46-9de6-fda64bbe6d2c"),
                            Email = "user92@example.com",
                            Gender = 0,
                            Name = "User92",
                            Password = "$2a$11$9LhLU7dIP8wyxkFrqX2xIeFps7wppZz.VxwGS1HsZVqf8IV3zaCM6",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("bb2a45f9-a07f-4739-9b20-4bbd46bae07b"),
                            Email = "user93@example.com",
                            Gender = 1,
                            Name = "User93",
                            Password = "$2a$11$AoeXRBSL5mAv7bdKc3/hjuc9OmgRqaSp/.Ro32O/7.xwkDVxFW3Ka",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c7f5132d-d706-423b-a3af-f90611469788"),
                            Email = "user94@example.com",
                            Gender = 0,
                            Name = "User94",
                            Password = "$2a$11$29V2f1Xg6XgMR424XBE/9eHlCJgRWITbQ0r7cDQKJPUiuw5vNK6Mq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("64be8ba5-604f-42ad-a339-0f1ee7142c93"),
                            Email = "user95@example.com",
                            Gender = 1,
                            Name = "User95",
                            Password = "$2a$11$wmX2ZvW30PgGAFljePg2x.lYxXmGbmZhqE8spmPgUiWIdwqlusmpO",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3ce04e3a-186a-4bd6-8ffe-47f210341b25"),
                            Email = "user96@example.com",
                            Gender = 0,
                            Name = "User96",
                            Password = "$2a$11$xDaX6xvIT4jRTEGHeHA8b.auJYfToAzRvkgqZBL8htRWzeANBWqci",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("dc3d38c0-a982-4635-94a5-61807d522432"),
                            Email = "user97@example.com",
                            Gender = 1,
                            Name = "User97",
                            Password = "$2a$11$h9Dw/Kd2EfE/WQ.E/OyR5.66cp.JFqIt88uAjKdmDHLkWr6O.Ny2W",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6f384cfd-1a56-48a8-bb98-65fa0dbca5d6"),
                            Email = "user98@example.com",
                            Gender = 0,
                            Name = "User98",
                            Password = "$2a$11$hjajZdBO3bhb7NRP1xV4F.TZ.8AiJ4TtHBi1WfdTenm.NNDUmNZBe",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c0bee675-885f-4ff8-9fe6-be7d18aa2538"),
                            Email = "user99@example.com",
                            Gender = 1,
                            Name = "User99",
                            Password = "$2a$11$qJ48j/WFlojPJP6Ig0mZNuJT/EPugQK62TUPdhZMUyCupRyYs9Dsm",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("c01ede05-beff-4344-b664-f22eba96a23e"),
                            Email = "user100@example.com",
                            Gender = 0,
                            Name = "User100",
                            Password = "$2a$11$kr.7A5lAyGa7JwvPW8uYle.1jSQHIE1ogmzsWpbRfhJvuE5PccQQq",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.HasOne("PassSystemTD.Entities.User", "User")
                        .WithMany("Passes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Proof", b =>
                {
                    b.HasOne("PassSystemTD.Entities.Pass", "Pass")
                        .WithMany("Proofs")
                        .HasForeignKey("PassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Role", b =>
                {
                    b.HasOne("PassSystemTD.Entities.User", "User")
                        .WithOne("Role")
                        .HasForeignKey("PassSystemTD.Entities.Role", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("PassSystemTD.Entities.User", b =>
                {
                    b.Navigation("Passes");

                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
