// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PassSystemTD.Data;

#nullable disable

namespace PassSystemTD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250303151420_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PassStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Proof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PassId");

                    b.ToTable("Proofs");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDean")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9a8841c-7340-4697-925a-d94d9f0cc3c1"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("0db5e0c8-1b1b-458d-a5fd-498cc6ce46a1"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("9bb3e152-bb6d-4b4f-afb8-adb8e7be5626"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("0714ae77-2022-42cf-981b-c1388b8cbfea"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("20285f4a-1ca0-4c1b-96ea-651cad573357"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("dc0b5186-b7ef-43dd-ba95-c3d16d0f9d47"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("5e578f88-4238-4351-9fe3-695a38353fd9"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("0ad6d62a-41ea-4129-8d3e-2eac56e7baac"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("df187816-efe3-4894-86d1-a74d2858a50c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6f9350a0-c47f-4579-8bfa-ed2533fb9d19"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("fdc9f9a5-56fd-42c8-8d44-8e45e975288b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("39513620-8006-46ea-b5d7-bd42c238a9c9"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("4cf48994-46d1-43bb-b1a4-42fd43de96df"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b2db4b69-d922-4ec3-8991-1db12ef84aa0"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("2708b88a-a0ab-4358-baca-b9108a7ecdf5"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("4667e5f0-e317-4055-856b-700886f17626"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d7852dda-7cec-4e14-a9bb-5c86d7b5b3c3"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("3b70981f-c60a-4af4-8a88-d5a7a7449472"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b81c2f99-6dde-41d2-a940-6a261af8a03a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c772b7db-9a40-4ccf-a6a2-920ece594c65"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("41c13004-c5ec-4d32-920f-4d2945dc3cd6"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("62774a3d-2583-4697-9e3e-6fd59a81af15"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("53ec0356-b063-47a2-ad6f-8b3452a5fb01"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c0573f21-c5be-4648-8907-c529a921748d"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6747d693-00f8-42b8-afe7-fc6bbe093045"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("a6fa09bc-d822-4d73-a261-19d73364aab9"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("8cdc7b55-d18c-414a-b7ca-12de2869ff9f"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6b4a9c91-a0fe-41db-a504-ca6569d39f68"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("e6c517e3-1bbe-4723-aa4e-49e1c873e8be"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b81ed8ed-938a-4309-81fd-cca9dac6534a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("dff221dd-d92a-4780-b09a-2d4bb02ef8dc"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d4486a21-7f32-4dc3-b2fa-03498f880075"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("37ee2938-6c9e-4a8a-8baf-cf012bd4872b"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("f586d4ee-9646-480f-850b-785ec7b870e3"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("b258f8ee-8118-4e5a-b0b9-2d42b181da73"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("776002bf-c810-40e6-a811-b501136195cd"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("f0b83541-1365-4839-88c1-df5ae112cb05"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("8bd090a4-e7b1-4f00-9222-dafdc9e828ff"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("a06a8ec0-8d77-4549-ab96-82e2f545a0b6"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("3ac05134-b1c1-4734-849d-76559018649a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("cbd0a31f-6bb6-4701-b752-2af009570ec9"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d2a95c02-0386-4264-9696-20d496075715"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d95ac8e6-1e8d-47d6-991d-7956470feb2a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("a4f3b11c-c45f-4d23-978b-200ade902e90"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("ccd681d3-89ce-44c9-955b-29b477041988"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("26f9cd13-e2a1-4447-ae89-9a7d51adcdba"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("14e7d3fc-c460-474b-8e9a-2074d369feab"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("3100c226-9d93-4f99-a883-a4593886d1e7"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("27e739fa-1a72-4971-a85e-21a568e32435"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("7a68a9e9-de85-4b0e-8927-039867a34f9a"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("669c8f67-7a81-4afa-8640-a70c17e667ab"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("d45ea3f4-3bc9-498e-889f-82dcf968bce9"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6fd4fe33-2abb-46f8-9e2c-dfe306fa57f8"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("4f632d81-2639-436a-a60a-616a04e01421"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1dcaf388-9d9b-42d4-b72e-f969013443bf"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("18206ff6-a98b-4de8-b325-304c49e8351d"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c8ef223a-a8cd-4acc-8eaf-2e08c1e6a76e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("63e165ac-06ed-432f-ba9f-cb52b732d4ed"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("157f0bdc-97f6-43db-b867-13102374e719"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("0f675390-389f-41a0-9b62-534802da2335"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("3de3f7bd-5869-488c-9454-fcc40a1558b5"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("5001e974-e693-49cc-a78d-8b4e78352ded"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("88a854c6-2455-4446-b568-97d6724c065b"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("e59b1421-26d3-4f93-a9aa-871160869bc5"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1e755de5-0532-4834-991c-d6d35793b58c"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("f351bc0b-6573-4dca-be68-6d50f0a59b40"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("9ad334e1-784a-4229-b1ba-161b652fbc94"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1a47d877-41ff-46ce-934b-27c58ba72c26"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("dcbb9a2e-e021-4268-ab08-bf04914f1ff1"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("3e99fe4c-c9d4-4354-8944-311a0da24fdb"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("2efc4a6c-c4b1-452f-aa8a-96faf29db414"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("3ccfce1a-3fbf-4812-a89c-cde8027e6e7e"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("facc6fd2-cac5-473b-be29-9ebd328a74ad"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("c3732540-7fc8-435b-97b0-30f033c9c23d"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6995a437-1af4-45cb-b579-0e47604adfce"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("663a2e07-5b81-47fa-802c-0dbedf8e0295"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("7927e736-e5bb-42c1-b9e1-3603aa1aea6c"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("8db1d91d-89c9-447c-a39c-86f208cdd288"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("441505bf-b2d8-421c-8e07-679133a4a352"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("4fa43eae-1355-4255-b305-2fad4f4560dc"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("533f1369-d29c-4799-87cb-087d3aeae718"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("2574874c-abb1-40c9-83ee-7745b4e61e41"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("e15f9a3f-bb9b-4cc8-9b73-81b92d84cabb"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6995c92a-311c-48b5-b983-e68d09b701eb"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("e61b5b75-242c-4fcd-ac51-3c8846cc85e9"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("46d9f511-ea71-4552-a072-5a84bf6b1ad3"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("670ad33a-bb1a-4e68-a826-270bd11894dd"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("f29d9194-3e5d-48c0-be66-681938ff45c2"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("5dedd314-a68c-4bd9-a459-63135bf403d7"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("a39b1f79-26a2-4c6e-a649-fda73b69f994"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("3ff30d8a-1d70-493c-ba4d-a87cea6ef7c5"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("df29860a-7a1b-424d-bce1-e884b8955ebe"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("81288061-e254-4522-854b-dd1ed92a595d"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("6dfff323-e4ec-48ad-8563-c283a9d0e9fb"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("a05fac61-bd08-46b8-a88b-676a7dd020f7"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        },
                        new
                        {
                            Id = new Guid("e948ecd9-01c8-42eb-9eb1-e8d53aecc629"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("e6f4c8f0-43fd-4b45-990e-9e4937439947"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("804dc86f-cc5c-4590-b6d4-dd46e60293e8"),
                            IsAdmin = false,
                            IsDean = true,
                            IsStudent = false,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("4da2da52-cb8b-4ec8-be25-880470dd1551"),
                            IsAdmin = false,
                            IsDean = false,
                            IsStudent = true,
                            IsTeacher = false
                        },
                        new
                        {
                            Id = new Guid("1e1125b2-639d-4069-937c-f3b49e599bdd"),
                            IsAdmin = true,
                            IsDean = false,
                            IsStudent = false,
                            IsTeacher = true
                        });
                });

            modelBuilder.Entity("PassSystemTD.Entities.TokenEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Token");

                    b.ToTable("BannedTokens");
                });

            modelBuilder.Entity("PassSystemTD.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9a8841c-7340-4697-925a-d94d9f0cc3c1"),
                            Email = "user1@example.com",
                            Gender = 1,
                            Name = "User1",
                            Password = "$2a$11$XSAD0kaua6lIhxA791lAGOt768ZCNFKkHtNT5XZQHGnSepOktYVJO"
                        },
                        new
                        {
                            Id = new Guid("0db5e0c8-1b1b-458d-a5fd-498cc6ce46a1"),
                            Email = "user2@example.com",
                            Gender = 0,
                            Name = "User2",
                            Password = "$2a$11$JlYlSoEkfnu7GIGo24znAOr0r9oULFaETh19zkiHCicX6UKLXcr5u"
                        },
                        new
                        {
                            Id = new Guid("9bb3e152-bb6d-4b4f-afb8-adb8e7be5626"),
                            Email = "user3@example.com",
                            Gender = 1,
                            Name = "User3",
                            Password = "$2a$11$3CyRAK/EINFn/fZXOYQlUeCWTz5rbaX.ZSgoP3YIEN414sQCJTDyS"
                        },
                        new
                        {
                            Id = new Guid("0714ae77-2022-42cf-981b-c1388b8cbfea"),
                            Email = "user4@example.com",
                            Gender = 0,
                            Name = "User4",
                            Password = "$2a$11$HsUFJLNYhgl.yEf6FQz36e7JYFpoJeIP5QO0i3yu9N.BBXA6YJSdu"
                        },
                        new
                        {
                            Id = new Guid("20285f4a-1ca0-4c1b-96ea-651cad573357"),
                            Email = "user5@example.com",
                            Gender = 1,
                            Name = "User5",
                            Password = "$2a$11$IekcLcsMxzx2UB8OhRdnwOWZYo/r3hEX0yU.vvVB6/g5LZzwVjBgy"
                        },
                        new
                        {
                            Id = new Guid("dc0b5186-b7ef-43dd-ba95-c3d16d0f9d47"),
                            Email = "user6@example.com",
                            Gender = 0,
                            Name = "User6",
                            Password = "$2a$11$gsczxr0mqB21gaixm8aQUuRdqrIKO.y8hFpzWo/tCXDMULeRVphBq"
                        },
                        new
                        {
                            Id = new Guid("5e578f88-4238-4351-9fe3-695a38353fd9"),
                            Email = "user7@example.com",
                            Gender = 1,
                            Name = "User7",
                            Password = "$2a$11$PRGdgfHgSds.D3kmOMCg6ebluiDv4JhkFH4lPQ0RnS/LvCS/npQFK"
                        },
                        new
                        {
                            Id = new Guid("0ad6d62a-41ea-4129-8d3e-2eac56e7baac"),
                            Email = "user8@example.com",
                            Gender = 0,
                            Name = "User8",
                            Password = "$2a$11$2lf.nW52po0PBKv8dFxfnuhauqVN8aBB2QgoTlVsMdl0od8S5A676"
                        },
                        new
                        {
                            Id = new Guid("df187816-efe3-4894-86d1-a74d2858a50c"),
                            Email = "user9@example.com",
                            Gender = 1,
                            Name = "User9",
                            Password = "$2a$11$bWDZ9b.Fqb5c5qPzDGeP0OvczksD4Sad4sXOY9Fxbquk8JMGHhGvW"
                        },
                        new
                        {
                            Id = new Guid("6f9350a0-c47f-4579-8bfa-ed2533fb9d19"),
                            Email = "user10@example.com",
                            Gender = 0,
                            Name = "User10",
                            Password = "$2a$11$9OH3xYwx8hf9hQAva8xpaulicXiNxD4D9c0GaYZWbejkNiEXQkMVG"
                        },
                        new
                        {
                            Id = new Guid("fdc9f9a5-56fd-42c8-8d44-8e45e975288b"),
                            Email = "user11@example.com",
                            Gender = 1,
                            Name = "User11",
                            Password = "$2a$11$pH0CQnKrqUGvPpi84bxh1e0dJPYw3ha6W6nQ36EFY2D5lmKKAcoMG"
                        },
                        new
                        {
                            Id = new Guid("39513620-8006-46ea-b5d7-bd42c238a9c9"),
                            Email = "user12@example.com",
                            Gender = 0,
                            Name = "User12",
                            Password = "$2a$11$50PHELXN0hkGLlBnJNdfcOxlkiXHPvj1oo0UEepAvM3ZGUpJPnqmC"
                        },
                        new
                        {
                            Id = new Guid("4cf48994-46d1-43bb-b1a4-42fd43de96df"),
                            Email = "user13@example.com",
                            Gender = 1,
                            Name = "User13",
                            Password = "$2a$11$dyecv5IPz3avpwsEix4aD.XDpmc7Ck7AHMrProHqZ0xcpfVNTyTti"
                        },
                        new
                        {
                            Id = new Guid("b2db4b69-d922-4ec3-8991-1db12ef84aa0"),
                            Email = "user14@example.com",
                            Gender = 0,
                            Name = "User14",
                            Password = "$2a$11$dgKwFFQYKHBlDGxwrEd0l.KRdBAq3iQR9FO4pnGwPmYXYC6/J7G72"
                        },
                        new
                        {
                            Id = new Guid("2708b88a-a0ab-4358-baca-b9108a7ecdf5"),
                            Email = "user15@example.com",
                            Gender = 1,
                            Name = "User15",
                            Password = "$2a$11$G90y47Zjm/EXJsMu6lLEn.aPBycRCl9gIG1gCgHOhoQCav7mxLEKu"
                        },
                        new
                        {
                            Id = new Guid("4667e5f0-e317-4055-856b-700886f17626"),
                            Email = "user16@example.com",
                            Gender = 0,
                            Name = "User16",
                            Password = "$2a$11$NQIC1u20p72JeVJqBTOcvOJ8q4tAAEKbhkQg81fL0kJLuqNVBiM0i"
                        },
                        new
                        {
                            Id = new Guid("d7852dda-7cec-4e14-a9bb-5c86d7b5b3c3"),
                            Email = "user17@example.com",
                            Gender = 1,
                            Name = "User17",
                            Password = "$2a$11$OFE/0Q7N92FkhEDEtXDCluLMNichfj5iBkw/5/55ga6d9ciNmMKrq"
                        },
                        new
                        {
                            Id = new Guid("3b70981f-c60a-4af4-8a88-d5a7a7449472"),
                            Email = "user18@example.com",
                            Gender = 0,
                            Name = "User18",
                            Password = "$2a$11$S0eAQgTXTpaQM2Js9CEoiO0uSi7qO3lbIw026/ZVJ0tvgWkcAE2c6"
                        },
                        new
                        {
                            Id = new Guid("b81c2f99-6dde-41d2-a940-6a261af8a03a"),
                            Email = "user19@example.com",
                            Gender = 1,
                            Name = "User19",
                            Password = "$2a$11$Rp8muaMkUKJX7JQOh2JBkuPHwYnL1eJG8ER/YvdTPs6LHnMLAYp42"
                        },
                        new
                        {
                            Id = new Guid("c772b7db-9a40-4ccf-a6a2-920ece594c65"),
                            Email = "user20@example.com",
                            Gender = 0,
                            Name = "User20",
                            Password = "$2a$11$Be2egp0mZnn.zCylnmE5XOyhh75inezvLFFdUlZZN9ul0kTVfXLUm"
                        },
                        new
                        {
                            Id = new Guid("41c13004-c5ec-4d32-920f-4d2945dc3cd6"),
                            Email = "user21@example.com",
                            Gender = 1,
                            Name = "User21",
                            Password = "$2a$11$rUSrERRU.ez5/v0VfQz/9u3JXQ4LnJLJgHpBrRdB9FoXWHTDOHy4."
                        },
                        new
                        {
                            Id = new Guid("62774a3d-2583-4697-9e3e-6fd59a81af15"),
                            Email = "user22@example.com",
                            Gender = 0,
                            Name = "User22",
                            Password = "$2a$11$RO4pkkMjVi8fVcZqZvfNX.vx8ZwW7LB8MoiMipH7wwOYHpEsfIdrO"
                        },
                        new
                        {
                            Id = new Guid("53ec0356-b063-47a2-ad6f-8b3452a5fb01"),
                            Email = "user23@example.com",
                            Gender = 1,
                            Name = "User23",
                            Password = "$2a$11$BNyq2UQCs8oxc2Fn95jsnuaN6/jiEq8SwoI5gWE4TcZqXNpwIVj/i"
                        },
                        new
                        {
                            Id = new Guid("c0573f21-c5be-4648-8907-c529a921748d"),
                            Email = "user24@example.com",
                            Gender = 0,
                            Name = "User24",
                            Password = "$2a$11$aktiuRsRCdgG5IT/QD1rNO5iNcFhtfUF0Oq2YoOkRmkVBrmLUGWB2"
                        },
                        new
                        {
                            Id = new Guid("6747d693-00f8-42b8-afe7-fc6bbe093045"),
                            Email = "user25@example.com",
                            Gender = 1,
                            Name = "User25",
                            Password = "$2a$11$A2dPqYxqjCZ9TOUMjRSgSuD8xYG4N20A0CjJ/.1bb1l/abMJbnG2S"
                        },
                        new
                        {
                            Id = new Guid("a6fa09bc-d822-4d73-a261-19d73364aab9"),
                            Email = "user26@example.com",
                            Gender = 0,
                            Name = "User26",
                            Password = "$2a$11$1oYSpTAGpwE.EjKiv32gm.adhUUVyIWIe6zziHVJ6oMkv4ux4GNWK"
                        },
                        new
                        {
                            Id = new Guid("8cdc7b55-d18c-414a-b7ca-12de2869ff9f"),
                            Email = "user27@example.com",
                            Gender = 1,
                            Name = "User27",
                            Password = "$2a$11$NpcaeS4NrxX.tYlMMS83i.rTQ09S6IHRHN16rZyxEvkrJMp359COO"
                        },
                        new
                        {
                            Id = new Guid("6b4a9c91-a0fe-41db-a504-ca6569d39f68"),
                            Email = "user28@example.com",
                            Gender = 0,
                            Name = "User28",
                            Password = "$2a$11$slWqwOYWX0koY5lmgaUIhuu7i1McIe0GRpcmtPQeYusdPA11J392K"
                        },
                        new
                        {
                            Id = new Guid("e6c517e3-1bbe-4723-aa4e-49e1c873e8be"),
                            Email = "user29@example.com",
                            Gender = 1,
                            Name = "User29",
                            Password = "$2a$11$fHTAbCBfOpdL.A3YWyj0f.zlkHTHWPwtAceCj88851OPYfXCaqeP6"
                        },
                        new
                        {
                            Id = new Guid("b81ed8ed-938a-4309-81fd-cca9dac6534a"),
                            Email = "user30@example.com",
                            Gender = 0,
                            Name = "User30",
                            Password = "$2a$11$gByPB2Dblxh.fzqDbStbN.8sMjkQ8gn.diQgPh0oCd6spjeLq7FNq"
                        },
                        new
                        {
                            Id = new Guid("dff221dd-d92a-4780-b09a-2d4bb02ef8dc"),
                            Email = "user31@example.com",
                            Gender = 1,
                            Name = "User31",
                            Password = "$2a$11$eIA6eovHdQExHLg719fko.DBlFaePzbaarkr2XS8VDwzw0Do1lAWm"
                        },
                        new
                        {
                            Id = new Guid("d4486a21-7f32-4dc3-b2fa-03498f880075"),
                            Email = "user32@example.com",
                            Gender = 0,
                            Name = "User32",
                            Password = "$2a$11$cBEQpW8laKFJFIYE8mOJ4OI5CKEnMFp63Wv3O8uGsv8/qAaICTC5W"
                        },
                        new
                        {
                            Id = new Guid("37ee2938-6c9e-4a8a-8baf-cf012bd4872b"),
                            Email = "user33@example.com",
                            Gender = 1,
                            Name = "User33",
                            Password = "$2a$11$gVpdj4X4NmqK4UMGCl.3Mu0Dy8pb4BJ8vZFJU3NdgF8H3OSbF.E8i"
                        },
                        new
                        {
                            Id = new Guid("f586d4ee-9646-480f-850b-785ec7b870e3"),
                            Email = "user34@example.com",
                            Gender = 0,
                            Name = "User34",
                            Password = "$2a$11$soAXMYVXhucWAEHlEqxwKec8ErRsrdzhwAvvBKTcxp/EiOy8LNu3a"
                        },
                        new
                        {
                            Id = new Guid("b258f8ee-8118-4e5a-b0b9-2d42b181da73"),
                            Email = "user35@example.com",
                            Gender = 1,
                            Name = "User35",
                            Password = "$2a$11$89eEgrZqdf92YE0931yhPe5tFBCt/J17XQCmwpv/yWI7YTI3gIDlW"
                        },
                        new
                        {
                            Id = new Guid("776002bf-c810-40e6-a811-b501136195cd"),
                            Email = "user36@example.com",
                            Gender = 0,
                            Name = "User36",
                            Password = "$2a$11$hdTPbt/9qnw8wDOR6dwynOxXz7Zkm6AvxOpG6llibO.Kebikm9Ir."
                        },
                        new
                        {
                            Id = new Guid("f0b83541-1365-4839-88c1-df5ae112cb05"),
                            Email = "user37@example.com",
                            Gender = 1,
                            Name = "User37",
                            Password = "$2a$11$PL4WN1wxzI2MsdKASqNAyuC45wRcFHXc8G1F2VHvT1TyQw2lbzJ5K"
                        },
                        new
                        {
                            Id = new Guid("8bd090a4-e7b1-4f00-9222-dafdc9e828ff"),
                            Email = "user38@example.com",
                            Gender = 0,
                            Name = "User38",
                            Password = "$2a$11$zXRogTSxKzJ9TJwJ4H8w2OwDx6pAnKigQ9EztTo32Ujs1AOjUKZ6W"
                        },
                        new
                        {
                            Id = new Guid("a06a8ec0-8d77-4549-ab96-82e2f545a0b6"),
                            Email = "user39@example.com",
                            Gender = 1,
                            Name = "User39",
                            Password = "$2a$11$pK5hT8uEbi8kzT4k3G1fvuViC7Rd.mpOqSi6UDfqvIQjCggpDPHEW"
                        },
                        new
                        {
                            Id = new Guid("3ac05134-b1c1-4734-849d-76559018649a"),
                            Email = "user40@example.com",
                            Gender = 0,
                            Name = "User40",
                            Password = "$2a$11$73XdunzFEX67HPuc3dl1yeLtDGmhe4/KEMO0h6G9pMhAPiOMY9R4e"
                        },
                        new
                        {
                            Id = new Guid("cbd0a31f-6bb6-4701-b752-2af009570ec9"),
                            Email = "user41@example.com",
                            Gender = 1,
                            Name = "User41",
                            Password = "$2a$11$l1N5N8psIeVYA5hMmIiQ2uIC9EJnwKFcb1VW1/PuPv5KThYXnElEy"
                        },
                        new
                        {
                            Id = new Guid("d2a95c02-0386-4264-9696-20d496075715"),
                            Email = "user42@example.com",
                            Gender = 0,
                            Name = "User42",
                            Password = "$2a$11$VyJ9rGaXZ2iNYJJh1NuQkeZye60GaL/FcdBpiMxGG1dLrXcbGESke"
                        },
                        new
                        {
                            Id = new Guid("d95ac8e6-1e8d-47d6-991d-7956470feb2a"),
                            Email = "user43@example.com",
                            Gender = 1,
                            Name = "User43",
                            Password = "$2a$11$zvFgc4BP2sP7da1m8EqH/OsLX16s9l.0KfIdb8bMo7fAh/EuN5alq"
                        },
                        new
                        {
                            Id = new Guid("a4f3b11c-c45f-4d23-978b-200ade902e90"),
                            Email = "user44@example.com",
                            Gender = 0,
                            Name = "User44",
                            Password = "$2a$11$7cWAdEqNOiydNwTftvXlmuMCreCxQhEn3wKr5syaEynPLOQq7fqdC"
                        },
                        new
                        {
                            Id = new Guid("ccd681d3-89ce-44c9-955b-29b477041988"),
                            Email = "user45@example.com",
                            Gender = 1,
                            Name = "User45",
                            Password = "$2a$11$wzYe1FKtZyGr4A/mlU1Kl.eWi6DyXv3xObWopduHCJUCLHJ6oUZgW"
                        },
                        new
                        {
                            Id = new Guid("26f9cd13-e2a1-4447-ae89-9a7d51adcdba"),
                            Email = "user46@example.com",
                            Gender = 0,
                            Name = "User46",
                            Password = "$2a$11$BTxTp2Bg7HojbOcmfDx4oelB2j6ldOVdJvrKsktMUg8yYy1l20W/a"
                        },
                        new
                        {
                            Id = new Guid("14e7d3fc-c460-474b-8e9a-2074d369feab"),
                            Email = "user47@example.com",
                            Gender = 1,
                            Name = "User47",
                            Password = "$2a$11$g10PEPEm6Sds47As1nEbweSjL6C4niUDEG/uFkpNNs/5PQwn6gBv."
                        },
                        new
                        {
                            Id = new Guid("3100c226-9d93-4f99-a883-a4593886d1e7"),
                            Email = "user48@example.com",
                            Gender = 0,
                            Name = "User48",
                            Password = "$2a$11$qyRxdcXU6LyzNKeWfxp5UuYRD5iwysoo8RNQ0ENZDiHOYYgwtI/h."
                        },
                        new
                        {
                            Id = new Guid("27e739fa-1a72-4971-a85e-21a568e32435"),
                            Email = "user49@example.com",
                            Gender = 1,
                            Name = "User49",
                            Password = "$2a$11$ndMbGN46KVcA8KlZQGAxI.zgH1rKLCyFWlge53IdtjxLqlYodmVwC"
                        },
                        new
                        {
                            Id = new Guid("7a68a9e9-de85-4b0e-8927-039867a34f9a"),
                            Email = "user50@example.com",
                            Gender = 0,
                            Name = "User50",
                            Password = "$2a$11$4jdXyU0Z/WLK4ck.CxQIMOH1Hqa/NDNk0qTr9ZQqwNA.tBitTMm7m"
                        },
                        new
                        {
                            Id = new Guid("669c8f67-7a81-4afa-8640-a70c17e667ab"),
                            Email = "user51@example.com",
                            Gender = 1,
                            Name = "User51",
                            Password = "$2a$11$mE3Y/VTjHJJvFNN28XUxue.d2dSjELEIAPMSuHLqJ3q.RycWssZfi"
                        },
                        new
                        {
                            Id = new Guid("d45ea3f4-3bc9-498e-889f-82dcf968bce9"),
                            Email = "user52@example.com",
                            Gender = 0,
                            Name = "User52",
                            Password = "$2a$11$ZpTscxVp5hXk369r3ZJplOkEB7kXI3oP50euS6rceLamB1GetUbmC"
                        },
                        new
                        {
                            Id = new Guid("6fd4fe33-2abb-46f8-9e2c-dfe306fa57f8"),
                            Email = "user53@example.com",
                            Gender = 1,
                            Name = "User53",
                            Password = "$2a$11$iXSPWQyF7L0YBp1Lup3O0OalLJzThO2zLAYimo6Gr8ONkhygEEg/S"
                        },
                        new
                        {
                            Id = new Guid("4f632d81-2639-436a-a60a-616a04e01421"),
                            Email = "user54@example.com",
                            Gender = 0,
                            Name = "User54",
                            Password = "$2a$11$7WZwrfbVrXlgPuQ1.KX4ouzBs5Y/qyeOOPiRnkx.qUBPe9kB25UDq"
                        },
                        new
                        {
                            Id = new Guid("1dcaf388-9d9b-42d4-b72e-f969013443bf"),
                            Email = "user55@example.com",
                            Gender = 1,
                            Name = "User55",
                            Password = "$2a$11$oCk8w2ucWIrXZpN55m4omOX03b6PwEN3jXAtR1hHIHdN9g/s2MrJe"
                        },
                        new
                        {
                            Id = new Guid("18206ff6-a98b-4de8-b325-304c49e8351d"),
                            Email = "user56@example.com",
                            Gender = 0,
                            Name = "User56",
                            Password = "$2a$11$R7kej.bpPhyy6/CcUWLut..S3uFbO.xNkxPjMiRKDspWSt5VbTcQ."
                        },
                        new
                        {
                            Id = new Guid("c8ef223a-a8cd-4acc-8eaf-2e08c1e6a76e"),
                            Email = "user57@example.com",
                            Gender = 1,
                            Name = "User57",
                            Password = "$2a$11$GyaE2B..82nSSUC1eI5YP.8uovlgTHfZ0N6OmDmjv.fAsMPqriee6"
                        },
                        new
                        {
                            Id = new Guid("63e165ac-06ed-432f-ba9f-cb52b732d4ed"),
                            Email = "user58@example.com",
                            Gender = 0,
                            Name = "User58",
                            Password = "$2a$11$dGAH.whxBYpNSnc2BpGe.uihkZqVy7I05EFw97qhzKZ4yc.K28F7q"
                        },
                        new
                        {
                            Id = new Guid("157f0bdc-97f6-43db-b867-13102374e719"),
                            Email = "user59@example.com",
                            Gender = 1,
                            Name = "User59",
                            Password = "$2a$11$6FSSVZUnIEJnTby4BCasLupp4V.Be8FAwatlxRYqgIMviSUCnGzgm"
                        },
                        new
                        {
                            Id = new Guid("0f675390-389f-41a0-9b62-534802da2335"),
                            Email = "user60@example.com",
                            Gender = 0,
                            Name = "User60",
                            Password = "$2a$11$gk05OsU05/pANnjeXej1Lu9PF8a5WB/a0stG3yWOe8nJiAYL/QG8W"
                        },
                        new
                        {
                            Id = new Guid("3de3f7bd-5869-488c-9454-fcc40a1558b5"),
                            Email = "user61@example.com",
                            Gender = 1,
                            Name = "User61",
                            Password = "$2a$11$RMlU63yakgwjwa0wX6l28uoDxjx6uUZMPWrZpkj671zj1ApNLPDdG"
                        },
                        new
                        {
                            Id = new Guid("5001e974-e693-49cc-a78d-8b4e78352ded"),
                            Email = "user62@example.com",
                            Gender = 0,
                            Name = "User62",
                            Password = "$2a$11$QMRH8aPxmGw5vJB7t8YrHOh5MW9JdR5HWvwDuDf0q.UKuzhtJAoz."
                        },
                        new
                        {
                            Id = new Guid("88a854c6-2455-4446-b568-97d6724c065b"),
                            Email = "user63@example.com",
                            Gender = 1,
                            Name = "User63",
                            Password = "$2a$11$2.36j/GsfLfl1AtMU4VvRuZyLf9fhV5xzU.oEq0tRgZRp6/Scgqx6"
                        },
                        new
                        {
                            Id = new Guid("e59b1421-26d3-4f93-a9aa-871160869bc5"),
                            Email = "user64@example.com",
                            Gender = 0,
                            Name = "User64",
                            Password = "$2a$11$uKjG1.7C4sPUve2MtzQ6EeRGRoMLXme8/S2oXOQDhNvL1.8nWsvEG"
                        },
                        new
                        {
                            Id = new Guid("1e755de5-0532-4834-991c-d6d35793b58c"),
                            Email = "user65@example.com",
                            Gender = 1,
                            Name = "User65",
                            Password = "$2a$11$DMXkdha8RmgX13AWGZNwP.fCFZRnASI0.AjMvbLRa1ru5I4q/KX8."
                        },
                        new
                        {
                            Id = new Guid("f351bc0b-6573-4dca-be68-6d50f0a59b40"),
                            Email = "user66@example.com",
                            Gender = 0,
                            Name = "User66",
                            Password = "$2a$11$f8Po/.RNMvBhlGTzrkEXUebn1TCee/T3FMNla8/A1tFsg76I17Zcq"
                        },
                        new
                        {
                            Id = new Guid("9ad334e1-784a-4229-b1ba-161b652fbc94"),
                            Email = "user67@example.com",
                            Gender = 1,
                            Name = "User67",
                            Password = "$2a$11$lOPHzA4d5RoRAU8ZvFpFTecjUgGxep1MHnfrkzRXnawh0gmfw0JNa"
                        },
                        new
                        {
                            Id = new Guid("1a47d877-41ff-46ce-934b-27c58ba72c26"),
                            Email = "user68@example.com",
                            Gender = 0,
                            Name = "User68",
                            Password = "$2a$11$/y1H6wKBHKN2F/K7FoAZ8O7uFGJpUZyGuHc.3W7LYhp4BHnBPm6.W"
                        },
                        new
                        {
                            Id = new Guid("dcbb9a2e-e021-4268-ab08-bf04914f1ff1"),
                            Email = "user69@example.com",
                            Gender = 1,
                            Name = "User69",
                            Password = "$2a$11$w/m4SxudOfnu4iShDXkaZOxzzHXgeYDAlGNHTucXkx8GSH.PVNmhm"
                        },
                        new
                        {
                            Id = new Guid("3e99fe4c-c9d4-4354-8944-311a0da24fdb"),
                            Email = "user70@example.com",
                            Gender = 0,
                            Name = "User70",
                            Password = "$2a$11$ozlVStpsx057u42gPioAKuS/5d/DJGtjI0pxRfgPgggzshi4uBqvS"
                        },
                        new
                        {
                            Id = new Guid("2efc4a6c-c4b1-452f-aa8a-96faf29db414"),
                            Email = "user71@example.com",
                            Gender = 1,
                            Name = "User71",
                            Password = "$2a$11$B9tWtmNJ9Gi9nsUB3X0qA.K1Ow9Y1YSwIwopLo3rDpHHa4eeT2FeO"
                        },
                        new
                        {
                            Id = new Guid("3ccfce1a-3fbf-4812-a89c-cde8027e6e7e"),
                            Email = "user72@example.com",
                            Gender = 0,
                            Name = "User72",
                            Password = "$2a$11$1laipALEumHTdlGHzOZH4eyz23tWOT.vKLFyJhpqj9/QLAXqaIONW"
                        },
                        new
                        {
                            Id = new Guid("facc6fd2-cac5-473b-be29-9ebd328a74ad"),
                            Email = "user73@example.com",
                            Gender = 1,
                            Name = "User73",
                            Password = "$2a$11$lz.vRfBVpAnRe.YpMgN/ke8TYWlYcQl14ctK5njYs.lALTUs.Rh8i"
                        },
                        new
                        {
                            Id = new Guid("c3732540-7fc8-435b-97b0-30f033c9c23d"),
                            Email = "user74@example.com",
                            Gender = 0,
                            Name = "User74",
                            Password = "$2a$11$K2mDSJFZ8GUVqeQzcKzu9u0ydLRRMz1dWM7HplMbekCD77MCTzwqK"
                        },
                        new
                        {
                            Id = new Guid("6995a437-1af4-45cb-b579-0e47604adfce"),
                            Email = "user75@example.com",
                            Gender = 1,
                            Name = "User75",
                            Password = "$2a$11$sej21UbNSPOpLpk4WtA07O/hkVgZ2Zu8OCfyDPaNSEutAt5V3z8H."
                        },
                        new
                        {
                            Id = new Guid("663a2e07-5b81-47fa-802c-0dbedf8e0295"),
                            Email = "user76@example.com",
                            Gender = 0,
                            Name = "User76",
                            Password = "$2a$11$z51hdofU22p6W/Ow0MX4K.kJB7JHTYBNFLTdbdhFYAnNRwqRo5AQK"
                        },
                        new
                        {
                            Id = new Guid("7927e736-e5bb-42c1-b9e1-3603aa1aea6c"),
                            Email = "user77@example.com",
                            Gender = 1,
                            Name = "User77",
                            Password = "$2a$11$Oh4PoDKrx2N2yGQd5DHo8OPT1uf.0G0Dyl4ROW2aO34Tc4yJlrZ1m"
                        },
                        new
                        {
                            Id = new Guid("8db1d91d-89c9-447c-a39c-86f208cdd288"),
                            Email = "user78@example.com",
                            Gender = 0,
                            Name = "User78",
                            Password = "$2a$11$ZlgGJ1LjP6mPGvL1LI/fr.8bfIkvVC6Cse8ZA/tSh2AMGvCWswaLC"
                        },
                        new
                        {
                            Id = new Guid("441505bf-b2d8-421c-8e07-679133a4a352"),
                            Email = "user79@example.com",
                            Gender = 1,
                            Name = "User79",
                            Password = "$2a$11$xQnG99ZMgtEMllNl/2wC6uumhTMQ/q.OiI.QHpGAKHxTlzjicA3iW"
                        },
                        new
                        {
                            Id = new Guid("4fa43eae-1355-4255-b305-2fad4f4560dc"),
                            Email = "user80@example.com",
                            Gender = 0,
                            Name = "User80",
                            Password = "$2a$11$Ldp5etAKNNbC00lsbwiAYecjFhIolYgHEl2Wi.5PdtoR7nn.0BTJ."
                        },
                        new
                        {
                            Id = new Guid("533f1369-d29c-4799-87cb-087d3aeae718"),
                            Email = "user81@example.com",
                            Gender = 1,
                            Name = "User81",
                            Password = "$2a$11$dlmecx5zin8TCmCm9SGiU.J1bJ3M.j/Ygt9SbEgB/bDZj.J5fGehq"
                        },
                        new
                        {
                            Id = new Guid("2574874c-abb1-40c9-83ee-7745b4e61e41"),
                            Email = "user82@example.com",
                            Gender = 0,
                            Name = "User82",
                            Password = "$2a$11$YB5b4LiJdIjWWzPYGkgKuOTjUO1APYC4dU9v1QNfZrG3BH3LypVDO"
                        },
                        new
                        {
                            Id = new Guid("e15f9a3f-bb9b-4cc8-9b73-81b92d84cabb"),
                            Email = "user83@example.com",
                            Gender = 1,
                            Name = "User83",
                            Password = "$2a$11$cekj1Pk7oXqsvvh8Upf7fugVXwMOkyQ.F8czhxu2J5bAks0DlsqNy"
                        },
                        new
                        {
                            Id = new Guid("6995c92a-311c-48b5-b983-e68d09b701eb"),
                            Email = "user84@example.com",
                            Gender = 0,
                            Name = "User84",
                            Password = "$2a$11$w1pcYihNFLLBXMsQ1.k73eotFvZQhMES4hGY4ofZMnFTju3gSGKuq"
                        },
                        new
                        {
                            Id = new Guid("e61b5b75-242c-4fcd-ac51-3c8846cc85e9"),
                            Email = "user85@example.com",
                            Gender = 1,
                            Name = "User85",
                            Password = "$2a$11$6eL7HCCOWaQJgUe8ky4S2OJuFU7.YsfeIb8rLpIhzLrDBMbcr/tVC"
                        },
                        new
                        {
                            Id = new Guid("46d9f511-ea71-4552-a072-5a84bf6b1ad3"),
                            Email = "user86@example.com",
                            Gender = 0,
                            Name = "User86",
                            Password = "$2a$11$oJa/IL5hShJFGEwV76I/GumLrD42/mZfa3OjKUp3eIkBUWGJ8nWEa"
                        },
                        new
                        {
                            Id = new Guid("670ad33a-bb1a-4e68-a826-270bd11894dd"),
                            Email = "user87@example.com",
                            Gender = 1,
                            Name = "User87",
                            Password = "$2a$11$KBLyj7/jo7pk40nTw0ZKZe8dozEw3GkyLy2j9t7dwzujCFPkgoIBy"
                        },
                        new
                        {
                            Id = new Guid("f29d9194-3e5d-48c0-be66-681938ff45c2"),
                            Email = "user88@example.com",
                            Gender = 0,
                            Name = "User88",
                            Password = "$2a$11$aAK2Xt1gCQEIrEamOxwo2ee3iu358eFQoN3SQ5z2TPF2aLbVsnKZW"
                        },
                        new
                        {
                            Id = new Guid("5dedd314-a68c-4bd9-a459-63135bf403d7"),
                            Email = "user89@example.com",
                            Gender = 1,
                            Name = "User89",
                            Password = "$2a$11$hFBH3yB0hXuscKEALjc0HOfcIeT1O6.CRelXoroHnfhHYG0iD9NtO"
                        },
                        new
                        {
                            Id = new Guid("a39b1f79-26a2-4c6e-a649-fda73b69f994"),
                            Email = "user90@example.com",
                            Gender = 0,
                            Name = "User90",
                            Password = "$2a$11$uNyM30HU7QA7Y42UcBX.wOs8A.tVzEAbq/qDpoC9mh1gdFywrG69C"
                        },
                        new
                        {
                            Id = new Guid("3ff30d8a-1d70-493c-ba4d-a87cea6ef7c5"),
                            Email = "user91@example.com",
                            Gender = 1,
                            Name = "User91",
                            Password = "$2a$11$LuOTEfWZF6xM0EfXcyXQhOJcMsq5iR/XEMVNibWMeNjtru9NcH5GC"
                        },
                        new
                        {
                            Id = new Guid("df29860a-7a1b-424d-bce1-e884b8955ebe"),
                            Email = "user92@example.com",
                            Gender = 0,
                            Name = "User92",
                            Password = "$2a$11$g/BewKFYevW99BssQT2.2.E9Kr5gZoc7VuYPRzWQ6YWWPWpsKV0cm"
                        },
                        new
                        {
                            Id = new Guid("81288061-e254-4522-854b-dd1ed92a595d"),
                            Email = "user93@example.com",
                            Gender = 1,
                            Name = "User93",
                            Password = "$2a$11$9YfQo0A8EYN4WqW51LdpF.W8HM4g/WX8NpZt5z3fkR3gYUt98qWIa"
                        },
                        new
                        {
                            Id = new Guid("6dfff323-e4ec-48ad-8563-c283a9d0e9fb"),
                            Email = "user94@example.com",
                            Gender = 0,
                            Name = "User94",
                            Password = "$2a$11$cViPpjRlKVPmDdU5kmRk/.sgJeabbf/zpT.2s03v3U4LXpTyPJiwe"
                        },
                        new
                        {
                            Id = new Guid("a05fac61-bd08-46b8-a88b-676a7dd020f7"),
                            Email = "user95@example.com",
                            Gender = 1,
                            Name = "User95",
                            Password = "$2a$11$7.wKgcYlY.p6RB1/3zHAj.GJ86h4iJHsUR1M/TmHds5UQx8l5iP52"
                        },
                        new
                        {
                            Id = new Guid("e948ecd9-01c8-42eb-9eb1-e8d53aecc629"),
                            Email = "user96@example.com",
                            Gender = 0,
                            Name = "User96",
                            Password = "$2a$11$XXa4nCN5QLd/2cibHGWF2udd.YZF9o8mUI05wM2aQE38kbLh.586S"
                        },
                        new
                        {
                            Id = new Guid("e6f4c8f0-43fd-4b45-990e-9e4937439947"),
                            Email = "user97@example.com",
                            Gender = 1,
                            Name = "User97",
                            Password = "$2a$11$88uIDcxoLnS93L1JtADV2OS3sjABgkpCcvkJA0/XJ.udpBXe/Xmfe"
                        },
                        new
                        {
                            Id = new Guid("804dc86f-cc5c-4590-b6d4-dd46e60293e8"),
                            Email = "user98@example.com",
                            Gender = 0,
                            Name = "User98",
                            Password = "$2a$11$Zs.HaDJteJRgqmE24/bs9.NEywyvn1q1FLlUty.fwNKpzSFlLjcES"
                        },
                        new
                        {
                            Id = new Guid("4da2da52-cb8b-4ec8-be25-880470dd1551"),
                            Email = "user99@example.com",
                            Gender = 1,
                            Name = "User99",
                            Password = "$2a$11$2EOFApJqhEjqwM5J/axv8OgieosB8qP4Tu5ftzXRmkFCTyBZlZmiS"
                        },
                        new
                        {
                            Id = new Guid("1e1125b2-639d-4069-937c-f3b49e599bdd"),
                            Email = "user100@example.com",
                            Gender = 0,
                            Name = "User100",
                            Password = "$2a$11$lCQeY3AAaPGOzPZbRYyCveuppwCeZHh.uLZ0aopwG.Nbt0fMe5eBW"
                        });
                });

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.HasOne("PassSystemTD.Entities.User", "Users")
                        .WithMany("Passes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Proof", b =>
                {
                    b.HasOne("PassSystemTD.Entities.Pass", "Pass")
                        .WithMany("Proofs")
                        .HasForeignKey("PassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Role", b =>
                {
                    b.HasOne("PassSystemTD.Entities.User", "User")
                        .WithOne("Role")
                        .HasForeignKey("PassSystemTD.Entities.Role", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PassSystemTD.Entities.Pass", b =>
                {
                    b.Navigation("Proofs");
                });

            modelBuilder.Entity("PassSystemTD.Entities.User", b =>
                {
                    b.Navigation("Passes");

                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
